<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Label="UserMacros">
	  <PT_INCLUDE_SEARCH_PATH>$(SolutionDir)include;$(SolutionDir)src\openssl\include;$(SolutionDir)src\Pt-Gfx\raster</PT_INCLUDE_SEARCH_PATH>
  </PropertyGroup>


  <PropertyGroup Label="UserMacros"
                 Condition="'$(Configuration)|$(Platform)'=='Jam Build|x64'">
    <PT_INCLUDE_SEARCH_PATH>$(PT_INCLUDE_SEARCH_PATH);$(SolutionDir)src\Pt-System\win32</PT_INCLUDE_SEARCH_PATH>
  </PropertyGroup>

  <PropertyGroup Label="UserMacros"
                 Condition="'$(Configuration)|$(Platform)'=='Jam Remote Build|x64'">
    <PT_INCLUDE_SEARCH_PATH>$(PT_INCLUDE_SEARCH_PATH);$(SolutionDir)src\Pt-Hmi\cocoa</PT_INCLUDE_SEARCH_PATH>
  </PropertyGroup>


  <PropertyGroup Label="UserMacros">
    <PT_INCLUDE_SEARCH_PATH>$(PT_INCLUDE_SEARCH_PATH);$(SolutionDir)src\blend2d\src</PT_INCLUDE_SEARCH_PATH>
  </PropertyGroup>


  <ImportGroup Label="PropertySheets">
    <Import Project="$(SolutionDir)Pt-user.props" 
            Condition="exists('$(SolutionDir)Pt-user.props')" />
  </ImportGroup>

</Project>
