/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_STATUS_H
#define COSMO_COMPONENT_STATUS_H

#include "DepenendcyInfo.h"

#include <Pt/Cosmo/Enumerable.h>
#include <Pt/Cosmo/AutoReleasePool.h>
#include <Pt/Cosmo/IComponentStatus.h>

#include <list>
#include <string>

namespace Pt {

namespace Cosmo {

class ComponentStatus : public IComponentStatus
{
  public:
    ComponentStatus()
    : _resolved(false)
    , _dependencyEnumerable(_pool, _dependencies)
    { }

    ComponentStatus(const ComponentStatus& other)
    : _dependencies(other._dependencies)
    , _resolved(other._resolved)
    , _pool()
    , _dependencyEnumerable(_pool, _dependencies)
    { }

    ComponentStatus& operator=(const ComponentStatus& other)
    {
      _pool.reset();
      _dependencies = other._dependencies;
      _resolved = other._resolved;
      _dependencyEnumerable.set(_pool, _dependencies);
      return *this;
    }

    bool isResolved() const
    { 
      return _resolved; 
    }

    void setResolved(bool isResolved)
    { 
      _resolved = isResolved; 
    }

    void addDependency(const std::string& featureId)
    {
      _dependencies.push_back( DependencyInfo(featureId) );
      _resolved = false;
    }

    void resetDependencies()
    {
      for(DependencyInfo& di : _dependencies)
      {
        di.setResolved(false);
        di.setInstance( std::string() );
      }

      _resolved = false;
    }

    std::list<DependencyInfo>& dependencies()
    {
      return _dependencies; 
    }

    const std::list<DependencyInfo>& dependencies() const
    {
      return _dependencies; 
    }

  protected:
    virtual const IEnumerable<IDependencyInfo>& onGetDependencies() const override
    {
      return _dependencyEnumerable;
    }

  private:
    std::list<DependencyInfo> _dependencies;
    bool                      _resolved;

    AutoReleasePool                            _pool;
    BasicEnumerable<std::list<DependencyInfo>,
                    IDependencyInfo>           _dependencyEnumerable;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
