/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#include "ComponentManagerImpl.h"
#include "ImportMap.h"
#include "ExportMap.h"
#include "Activator.h"

#include <Pt/Cosmo/IComponentPlugin.h>

#include <algorithm>
#include <chrono> // benchmark only
#include <iostream>  // benchmark only

namespace Pt {

namespace Cosmo {

ComponentManagerImpl::ComponentManagerImpl()
: _componentInfos(_pool, _components)
{
}


ComponentManagerImpl::~ComponentManagerImpl()
{
  while( ! _components.isEmpty() )
  {
    auto it = _components.begin();
    IComponentPlugin* plugin = it->second.plugin();
    unload(*plugin);
  }
}


void ComponentManagerImpl::setModulesDir(const std::string& dir)
{
  _modulesDir = dir;
}


void ComponentManagerImpl::importComponents(const std::string& manifest)
{
  ImportMap imports(manifest);

  for(const auto& entry : imports)
  {
    const Import& imp = entry.second;
    const std::string* symbol = ! imp.symbol().empty() ? &imp.symbol() : 0;
    
    IComponentPlugin* plugin = importComponent(imp.module(), imp.classId(), symbol);
    if(plugin)
      registerComponent(*plugin, imp.require(), imp.instance());
  }
}


IComponentPlugin* ComponentManagerImpl::importComponent(const std::string& module,
                                                        const std::string& classId,
                                                        const std::string* symbol)
{
  if( ! symbol )
  {
    std::string manifestName = module + ".ini";
    System::Path manifestPath = System::Path(_modulesDir.c_str()) / manifestName.c_str();

    ExportMap* exports = loadExports(manifestPath);
    if( ! exports )
      return 0;

    symbol = exports->findSymbol(classId);
    if( ! symbol )
      return 0;
  }

  const char* libraryPrefix = System::Library::prefix();
  const char* librarySuffix = System::Library::suffix();

  std::string fileName = libraryPrefix + module + librarySuffix;
  System::Path libraryPath = System::Path(_modulesDir.c_str()) / fileName.c_str();

  IComponentPlugin* plugin = loadPlugin(libraryPath.toLocal(), classId, *symbol);
  return plugin;
}


ExportMap* ComponentManagerImpl::loadExports(const System::Path& path)
{
  auto exports = _moduleExports.find( path.toLocal() );
  if( exports != _moduleExports.end() )
    return &exports->second;

  ExportMap exportMap( path.toLocal() );

  auto inserted = _moduleExports.insert( std::make_pair( path.toLocal(), exportMap) );
  return &inserted.first->second;
}


IComponentPlugin* ComponentManagerImpl::loadPlugin(const std::string& path,
                                                   const std::string& classId,
                                                   const std::string& symbolName)
{
  //
  // load the shared library
  //
  auto it = _modules.find(path);
  bool openLibrary = it == _modules.end();
  System::Library library;

  if(openLibrary)
  {
    library = System::Library( System::Path(path.c_str()) );
  }
  else
    library = it->second;

  //
  // get the component plugin symbol
  //
  void* symbol = library[ symbolName.c_str() ];
  if( ! symbol )
    return 0;

  IComponentPlugin** plugins = 0;
  plugins = reinterpret_cast<IComponentPlugin**>(symbol);

  //
  // add the shared library to the cache
  //
  if(openLibrary)
    _modules[path] = library;

  //
  // load the component plugin for the requested class ID
  //
  IComponentPlugin* found = 0;
  for(IComponentPlugin** plugin = plugins; *plugin != 0; ++plugin)
  {
    if( (*plugin)->classId() == classId)
    {
      found = *plugin;
      break;
    }
  }

  return found;
}


void ComponentManagerImpl::onRegisterComponent(IComponentPlugin& plugin,
                                               const std::string& require,
                                               const std::string& instanceId)
{
  //
  // unload component with same instance ID
  //
  bool replace = _components.find(instanceId) != _components.end();
  if(replace)
    unload(instanceId);

  _components.insert(&plugin, instanceId, require);

  resolve();
}


void ComponentManagerImpl::resolve()
{
  std::set<ComponentTable::Entry*> visited;
  
  static unsigned long long usecs = 0;
  auto start = std::chrono::steady_clock::now();

  for(ComponentTable::ValueType& entry : _components)
  {
    resolveComponent(entry.second, visited);
  }

  auto end = std::chrono::steady_clock::now();
  auto elapsed = end - start;
  usecs += std::chrono::duration_cast<std::chrono::microseconds>(elapsed).count();
  //std::cout << "resolved in: " << usecs/1000 << " msecs. " << '\n';
}


bool ComponentManagerImpl::resolveComponent(ComponentTable::Entry& entry, 
                                            std::set<ComponentTable::Entry*>& visited)
{
  auto vit = visited.find(&entry);
  if(vit != visited.end() )
    return (*vit)->status().isResolved();

  // TODO: setStatus instead of mutable reference to member
  ComponentStatus& status = entry.status();
  status.resetDependencies();

  ComponentTable::Entry* required = 0;
  const char* require = entry.require();
  if(*require != '\0')
  {
    auto it = _components.find( entry.require() );
    if( it == _components.end() )
    {
      visited.insert(&entry);
      return false;
    }

    required = &it->second;
  }
 
  bool isResolved = true;
  
  for( DependencyInfo& dep : status.dependencies() )
  {
    ComponentTable::Entry* found = 0;
    bool dependencyResolved = false;

    if( required && required->hasFeatureId( dep.featureId().c_str() ) )
      found = required;
    else
      found = _components.findDependency( dep.featureId() );

    if(found)
    {
      dependencyResolved = resolveComponent(*found, visited);
      dep.setTarget(found->instanceId(), dependencyResolved);  
    }

    isResolved = isResolved && dependencyResolved;
  }

  status.setResolved(isResolved);

  visited.insert(&entry);
  return entry.status().isResolved();
}


void ComponentManagerImpl::onLoad()
{
  //
  // create all auto-start components
  //
  for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
  {
    ComponentTable::Entry& entry = it->second;
    
    if( entry.mode().isAutoStart() )
      createComponent(entry);
  }

  //
  // create all connectable components
  //
  for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
  {
    ComponentTable::Entry& info = it->second;
    
    bool isCreated = info.component() != 0;
    if(isCreated)
      continue;

    auto findConnectable = [&info](ComponentTable::ValueType& entry)
    {
      Component* c = entry.second.component();
      if( ! c || c == info.component() )
        return false;

      IConnect* connect = c->queryInterface<IConnect>();
      return connect && connect->isConnectable(*info.plugin());
    };

    auto found = std::find_if(_components.begin(), _components.end(), findConnectable);
    if( found != _components.end() )
      createComponent(info);
  }
}


void ComponentManagerImpl::onLoadInstance(const std::string& instance)
{
  auto it = _components.find(instance);
  if( it == _components.end() )
    return;

  createComponent(it->second);
}


void ComponentManagerImpl::onUnload(IComponentPlugin& plugin)
{
  for(auto it = _components.begin(); it != _components.end(); )
  {
    ComponentTable::Entry& entry = it->second;

    if(entry.plugin() == &plugin)
    {
      removeComponent(entry);
      it = _components.erase(it);
    }
    else
      ++it;
  }

  resolve();
}


IComponentPlugin* ComponentManagerImpl::onUnloadInstance(const std::string& instanceId)
{
  auto it = _components.find(instanceId);
  if( it == _components.end() )
    return 0;

  ComponentTable::Entry& entry = it->second;
  IComponentPlugin* plugin = entry.plugin();
  
  removeComponent(entry);
  _components.erase(instanceId);

  resolve();

  return plugin;
}


const IEnumerable<ComponentInfo>& ComponentManagerImpl::onGetComponents() const
{
  return _componentInfos;
}


Component* ComponentManagerImpl::createComponent(ComponentTable::Entry& entry)
{
  //
  // check if already created
  //
  Component* instance = entry.component();
  if(instance)
    return instance;

  //
  // check if resolved
  //
  if( ! entry.status().isResolved() )
    return 0;

  //
  // create all dependencies
  //
  bool hasActivate = entry.info().hasInterface<IActivate>();
  Activator activator;

  const ComponentStatus& status = entry.status();
  for( const DependencyInfo& dep : status.dependencies() )
  {
    auto it = _components.find( dep.instanceId() );
    if( it == _components.end() )
      return 0;
    
    Component* c = createComponent(it->second);
    if( ! c )
      return 0;

    if( hasActivate )
      activator.add(dep.featureId(), c);
  }

  //
  // check if already created by a dependency that connnects to this component
  //
  instance = entry.component();
  if(instance)
    return instance;

  //
  // create component
  //
  Component* component = entry.create();
  if( ! component ) 
    return 0;

  //
  // activate component
  //
  IActivate* activate = component->queryInterface<IActivate>();
  if(activate)
  {
    activate->activate(activator);
  }

  //
  // add created component to instances which have IConnect
  //
  for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
  {
    Component* c = it->second.component();
    if( ! c )
      continue;

    IConnect* connect = c->queryInterface<IConnect>();
    if( connect && connect->isConnectable(*entry.plugin()) )
    {
      connect->addComponent(*component);
    }
  }

  //
  // add instances to created component which have IConnect
  //
  IConnect* connect = component->queryInterface<IConnect>();
  if(connect)
  {
    for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
    {
      Component* c = it->second.component();
      IComponentPlugin* p = it->second.plugin();

      if( ! c )
        continue;
      
      if( connect->isConnectable(*p) )
      {
        connect->addComponent(*c);
      }
    }
  }

  //
  // create all components this component can connect to
  //
  if(connect)
  {
    for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
    {
      ComponentTable::Entry& info = it->second;

      bool isConnectable = connect->isConnectable(*info.plugin());
      if(isConnectable)
      {
        createComponent(info);
      }
    }
  }

  return component;
}


void ComponentManagerImpl::removeComponent(ComponentTable::Entry& remove)
{
  Component* removedComponent = remove.component();
  if( ! removedComponent )
    return;

  //
  // disconnect removed component
  //
  IConnect* removedConnect = removedComponent->queryInterface<IConnect>();

  for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
  {
    IComponentPlugin* otherPlugin = it->second.plugin();
    Component* otherComponent = it->second.component();
    if( ! otherComponent )
      continue;

    // disconnect removed component from other components
    IConnect* otherConnect = otherComponent->queryInterface<IConnect>();
    if(otherConnect)
    {
      if( otherConnect->isConnectable(*remove.plugin()) )
        otherConnect->removeComponent(*removedComponent);
    }

    // disconnect other component from removed component
    if(removedConnect)
    {
      if( removedConnect->isConnectable(*otherPlugin) )
        removedConnect->removeComponent(*otherComponent);
    }
  }

  //
  // remove all components that depend on the removed component
  //
  for(ComponentTable::Iterator it = _components.begin(); it != _components.end(); ++it)
  {
    ComponentTable::Entry& entry = it->second;
    if( entry.dependsOn(remove.instanceId()) )
      removeComponent(entry);
  }

  //
  // deactivate removed component
  //  
  IActivate* removedActivate = removedComponent->queryInterface<IActivate>();
  if(removedActivate)
  {
    removedActivate->deactivate();
  }

  //
  // destroy removed components
  //
  remove.destroy();
}

} // namespace Cosmo

} // namespace Pt
