/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_MANAGER_IMPL_H
#define COSMO_COMPONENT_MANAGER_IMPL_H

#include <Pt/System/Path.h>
#include <Pt/System/Library.h>
#include "ComponentTable.h"

#include <Pt/Cosmo/AutoReleasePool.h>
#include <Pt/Cosmo/Enumerable.h>
#include <Pt/Cosmo/IComponentManager.h>

#include <string>
#include <map>
#include <set>

namespace Pt {

namespace Cosmo {

class ExportMap;

/** @brief Component manager implementation.
*/
class ComponentManagerImpl : public IComponentManager
{
  public:
    /** @brief Constructor.
    */
    ComponentManagerImpl();

    /** @brief Destructor.
    */
    ~ComponentManagerImpl();

    /** @brief Set modules search directory.
    */
    void setModulesDir(const std::string& dir);

    /** @brief Load all components from manifest.
    */
    void importComponents(const std::string& manifest);

  protected:
    // inherit docs
    virtual void onRegisterComponent(IComponentPlugin& plugin,
                                     const std::string& require,
                                     const std::string& instanceId) override;

    // inherit docs
    virtual void onLoad() override;

    // inherit docs
    virtual void onLoadInstance(const std::string& instance) override;
    
    // inherit docs
    virtual void onUnload(IComponentPlugin& plugin) override;

    // inherit docs
    virtual IComponentPlugin* onUnloadInstance(const std::string& instanceId) override;

    // inherit docs
    virtual const IEnumerable<ComponentInfo>& onGetComponents() const override;

  private:
    void resolve();

    bool resolveComponent(ComponentTable::Entry& entry, 
                          std::set<ComponentTable::Entry*>& visited);

    IComponentPlugin* importComponent(const std::string& module,
                                      const std::string& classId,
                                      const std::string* symbol = 0);

    ExportMap* loadExports(const System::Path& manifest);

    IComponentPlugin* loadPlugin(const std::string& path,
                                 const std::string& classId,
                                 const std::string& symbolName);

    Component* createComponent(ComponentTable::Entry& entry);

    void removeComponent(ComponentTable::Entry& entry);

  private:
    std::string                       _modulesDir;
    std::map<std::string, System::Library>    _modules;
    std::map<std::string, ExportMap>  _moduleExports;

    ComponentTable                    _components;
    AutoReleasePool                   _pool;
    ComponentInfoList                 _componentInfos;
};

} // namespace Cosmo

} // namespace Pt

#endif
