/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_TABLE_H
#define COSMO_COMPONENT_TABLE_H

#include "ComponentDeclaration.h"
#include "ComponentStatus.h"

#include <Pt/Cosmo/Enumerable.h>
#include <Pt/Cosmo/ComponentInfo.h>
#include <Pt/Cosmo/IAutoReleasePool.h>

#include <string>
#include <map>

namespace Pt {

namespace Cosmo {

class ComponentTable
{
  public:
    class Entry;

    typedef std::map<std::string, Entry> Components;
    typedef Components::iterator         Iterator;
    typedef Components::const_iterator   ConstIterator;
    typedef Components::value_type       ValueType;

  public:
    ComponentTable();

    ~ComponentTable();

    bool isEmpty() const
    { return _components.empty(); }

    ConstIterator begin() const
    { return _components.begin(); }

    ConstIterator end() const
    { return _components.end(); }

    Iterator begin()
    { return _components.begin(); }

    Iterator end()
    { return _components.end(); }

    ConstIterator find(const std::string& instanceId) const
    { return _components.find(instanceId); }

    Iterator find(const std::string& instanceId)
    { return _components.find(instanceId); }

    Iterator erase(Iterator it);

    void erase(const std::string& instanceId);

    void insert(IComponentPlugin* plugin,
                const std::string& instanceId,
                const std::string& require); 

    Entry* findDependency(const std::string& featureId);

  private:
    typedef std::multimap<std::string, Entry*> FeatureIds;

  private:
    AutoReleasePool _pool;
    Components      _components;
    FeatureIds      _featureIds;
};


class ComponentTable::Entry
{
  public:
    Entry(IComponentPlugin* plugin,
          const std::string& instanceId,
          const std::string& require);

    Entry(const Entry& other);

    Entry& operator=(const Entry& other);

    ComponentMode mode() const
    {
      return _info.mode();
    }

    bool hasFeatureId(const char* featureId) const
    {
      return _info.hasFeatureId(featureId);
    }

    const IEnumerable<const char*>& featureIds() const
    {
      return _info.featureIds();
    }

    const char* instanceId() const
    {
      return _info.instanceId();
    }

    const char* require() const
    {
      return _decl.require();
    }

    Component* component()
    { 
      return _component;
    }
    
    Component* create()
    {
      if(_component)
        return _component;

      _component = _plugin->create(&_decl);
      return _component;
    }

    void destroy()
    {
      if(_component)
      {
        _plugin->destroy(_component);
        _component = 0;
      }
    }

    bool dependsOn(const std::string& instanceId) const
    {
      for( const DependencyInfo& dep : _status.dependencies() )
      {
        if(dep.instanceId() == instanceId)
          return true;
      }

      return false;
    }

  public:
    IComponentPlugin* plugin()
    {
      return _plugin;
    }

    const IComponentPlugin* plugin() const
    {
      return _plugin;
    }

    ComponentDeclaration& declaration()
    {
      return _decl;
    }

    const ComponentDeclaration& declaration() const
    {
      return _decl;
    }

    ComponentStatus& status()
    {
      return _status;
    }

    const ComponentStatus& status() const
    {
      return _status;
    }

    ComponentInfo& info()
    {
      return _info;
    }

    const ComponentInfo& info() const
    {
      return _info;
    }

  private:
    IComponentPlugin*    _plugin;
    ComponentDeclaration _decl;
    ComponentStatus      _status;
    ComponentInfo        _info;   
    Component*           _component;
};


class ComponentInfoList : public IEnumerable<ComponentInfo>
{
  public:
    class Enumeration : public IEnumeration<ComponentInfo>
    {
      public:
        Enumeration(const ComponentTable& list)
        : _list(list)
        , _it( list.begin() )
        {  }

      protected:
        virtual bool onIsValid() const override
        {
          return _it != _list.end();
        }

        virtual void onAdvance() override
        {
          ++_it;
        }

        virtual const ComponentInfo& onGet() const override
        {
          return _it->second.info();
        }

      private:
        const ComponentTable&         _list;
        ComponentTable::ConstIterator _it;
    };

  public:
    ComponentInfoList(IAutoReleasePool& pool,
                      ComponentTable& table)
    : _pool(pool)
    , _table(table)
    { }

  protected:
    Cosmo::Enumerator<ComponentInfo> onEnumerate() const
    {
      Enumeration* e = new Enumeration(_table);
      auto deleter = [](Enumeration* e){ delete e; };
      return Cosmo::Enumerator<ComponentInfo>(_pool, e, deleter);
    }

  private:
    IAutoReleasePool& _pool;
    ComponentTable&   _table;
};

} // namespace Cosmo

} // namespace Pt

#endif
