/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#include <Pt/Cosmo/ComponentManager.h>
#include <Pt/Cosmo/IDependencyInfo.h>
#include <Pt/Cosmo/Main.h>

#include <Pt/Settings.h>

#include <iostream>
#include <string>

void printInfo(const Pt::Cosmo::ComponentInfo& ci)
{
  using namespace Pt::Cosmo;

  std::cout << "\n";
  std::cout << "CLASS ID    : " << ci.classId() << std::endl;
  std::cout << "INSTANCE ID : " << ci.instanceId() << std::endl;
  std::cout << "INFO        : " << ci.info() << std::endl;

  std::cout << "FEATURE IDs : ";
  for(const std::string& fid : ci.featureIds() )
    std::cout << fid << " ";
  std::cout << std::endl;

  std::cout << "\n";
  std::cout << "DEPENDENCIES:" << std::endl;

  Enumerator<IDependencyInfo> dep = ci.dependencies().enumerate();
  if( ! dep )
  {
    std::cout << " none";
    std::cout << std::endl;
  }

  for( ; dep; ++dep)
  {
    std::cout << "  " << dep->featureId();
    if( ! dep->isResolved() )
      std::cout << " (unresolved)";
    else
      std::cout << " (" << dep->instanceId() << ")";

    std::cout << std::endl;
  }
}


void onList(Pt::Cosmo::ComponentManager& cm, const std::string& info)
{
  std::cout << "\n";
  std::cout << "AVAILABLE COMPONENTS:\n";

  for( const Pt::Cosmo::ComponentInfo& ci : cm.components() )
  {
    std::cout << ci.instanceId();

    bool isFirst = true;
    for( auto featureId : ci.featureIds() )
    {
      if(isFirst)
      {
        std::cout << " (";
        isFirst = false;
      }
      else
        std::cout << ", ";

      std::cout << featureId;
    }

    std::cout << ")\n";
  }
}


void onInfo(Pt::Cosmo::ComponentManager& cm, const std::string& info)
{
  for(auto it = cm.components().enumerate(); it; ++it)
  {
    if(it->instanceId() == info)
    {
      printInfo(*it);
      return;
    }
  }

  std::cout << "No such component." << std::endl;
}


int main(int argc, char** argv)
{
  try
  {
    std::string modulesDir, modules, info;
    bool showList = false;
    for( int i = 1; i < argc; ++i )
    {
      std::string arg = argv[i];

      if( arg == "--modules-dir" )
      {
        if( ++i < argc )
          modulesDir = argv[i];
      }
      else if( arg == "--modules" )
      {
        if( ++i < argc )
          modules = argv[i];
      }
      else if( arg == "--info" )
      {
        if( ++i < argc )
          info = argv[i];
      }
      else if( arg == "--list" )
      {
        showList = true;
      }
    }

    Pt::Cosmo::ComponentManager cm;
    if( ! modulesDir.empty() )
      cm.setModulesDir(modulesDir);

    if( ! modules.empty() )
      cm.importComponents(modules);

    Pt::Cosmo::Main main(argc, argv, cm);

    if( ! info.empty() )
    {
      onInfo(cm, info);
      return 0;
    }

    if(showList)
    {
      onList(cm, info);
      return 0;
    }

    main.run();

    return 0;
  }
  catch(const Pt::SettingsError& se)
  {
    std::cerr << "settings error: " << se.what() << " (" << se.line() << ")" << std::endl;
  }
  catch(const std::exception& e)
  {
    std::cerr << "internal error: " << e.what() << " (" << typeid(e).name() << ")" << std::endl;
  }

  return 1;
}
