/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_DEPENDENCY_INFO_H
#define COSMO_DEPENDENCY_INFO_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IDependencyInfo.h>

#include <string>

namespace Pt {

namespace Cosmo {

/** @brief Dependency info.
*/
class DependencyInfo : public IDependencyInfo
{
  public:
    /** @brief Constructor.
    */
    DependencyInfo()
    : _isResolved(false)
    {
    }

    /** @brief Constructor.
    */
    explicit DependencyInfo(const std::string& featureId)
    : _featureId(featureId)
    , _isResolved(false)
    {
    }

    DependencyInfo(const std::string& featureId,
                   const std::string& instanceId,
                   bool isResolved)
    : _featureId(featureId)
    , _instanceId(instanceId)
    , _isResolved(isResolved)
    {
    }

    /** @brief Destructor.
    */
    ~DependencyInfo()
    {}

    void setResolved(bool resolved)
    {
      _isResolved = resolved;
    }

    void setInstance(const std::string& instanceId)
    {
      _instanceId = instanceId;
    }

    bool operator ==(const DependencyInfo& rhs) const
    {
      return _featureId == rhs._featureId &&
             _instanceId == rhs._instanceId &&
             _isResolved == rhs._isResolved;
    }

    bool operator !=(const DependencyInfo& rhs) const
    {
      return ! operator==(rhs);
    }

  protected:
    virtual const std::string& onGetFeatureId() const override
    {
      return _featureId;
    }

    virtual const std::string& onGetInstanceId() const override
    {
      return _instanceId;
    }

    virtual bool onIsResolved() const override
    {
      return _isResolved;
    }

    virtual void onSetTarget(const std::string& instanceId,
                             bool isResolved) override
    {
      _instanceId = instanceId;
      _isResolved = isResolved;
    }

  private:
    std::string  _featureId;
    std::string  _instanceId;
    bool         _isResolved;
};

} // namespace Cosmo

} // namespace Pt

#endif
