/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_IMPORTMAP_H
#define COSMO_IMPORTMAP_H

#include <Pt/Cosmo/Api.h>
#include <string>
#include <map>

namespace Pt {

namespace Cosmo {

class Import
{
  public:
    Import()
    {}

    Import(const std::string& classId,
           const std::string& module,
           const std::string& symbol,
           const std::string& instanceId)
    : _classId(classId)
    , _module(module)
    , _symbol(symbol)
    , _instanceId(instanceId)
    {
    }

    const std::string& classId() const
    { return _classId; }

    const std::string& module() const
    { return _module; }

    const std::string& symbol() const
    { return _symbol; }

    const std::string& instance() const
    { return _instanceId; }

    const std::string& require() const
    { return _require; }

    void setRequire(const std::string& require)
    { _require = require; }

  private:
    std::string _classId;
    std::string _module;
    std::string _symbol;
    std::string _require;
    std::string _instanceId;
};


class ImportMap
{
  public:
    typedef std::map<std::string, Import>::const_iterator ConstIterator;

  public:
    ImportMap(const std::string& appIni);

    ~ImportMap();

    ConstIterator begin() const
    { return _imports.begin(); }

    ConstIterator end() const
    { return _imports.end(); }

  private:
    std::map<std::string, Import> _imports;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
