/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_MAIN_COMPONENT_IMPLMENTATION_H
#define COSMO_MAIN_COMPONENT_IMPLMENTATION_H

#include <Pt/Cosmo/Main.h>
#include <Pt/Cosmo/IMain.h>
#include <Pt/Cosmo/IActivate.h>
#include <Pt/Cosmo/IConnect.h>

namespace Pt {

namespace Cosmo {

class ComponentManager;

/** @brief Main component implementation.
*/
class MainImpl : public Component
               , public IActivate
               , public IConnect
               , public IMain
{
  public:
    /** @brief Constructor..
    */
    MainImpl(int& argc, char** argv,
             ComponentManager& cm,
             MainPlugin& plugin);
    
    /** @brief Destructor.
    */
    ~MainImpl();

    /** @brief Launches the application.
    */
    void run();

  //
  // IActivate
  //
  protected:
    virtual void onActivate(const IActivator& cm) override;

    virtual void onDeactivate() override;

  //
  // IConnect
  //
  protected:
    virtual bool onIsConnectable(Cosmo::IComponentPlugin& p) const override;
    
    virtual void onComponentAdded(Cosmo::Component& c) override;

    virtual void onComponentRemoved(Cosmo::Component& c) override;
  
  //
  // IMain
  //
  protected:
    virtual int& onGetArgc() const
    { return _argc; }

    virtual char** onGetArgv() const
    { return _argv; }

  private:
    class ILauncher*    _launcher;
    bool                _isRunning;
    ComponentManager&   _cm;

    int&                _argc;
    char**              _argv;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
