" General options
set nocompatible
set hidden
set noerrorbells
set novisualbell
set showmode
set nobackup
set noswapfile
set nocp
winpos 0 0
set lines=999 columns=210
set guioptions-=L
set guioptions-=T
set mouse=a
set bs=2
set backspace=indent,eol,start whichwrap+=<,>,[,]
filetype plugin on
set number
set numberwidth=5
set ruler
set cursorline
set showmatch
set incsearch
set nofoldenable
set wrap
set wrapscan
set ignorecase
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set autoindent
set virtualedit=block,onemore
syntax on
colors pt
set guifont=Monaco:h10,Consolas:h9,Courier\ New:h10
set sessionoptions=buffers

" %= = sep. betweeen l/r-aligned      %n = buffer number
" %F = full path to file              %y = type of file
" %m = modified                       %r = readonly
" %b = value of byte                  %B = value of byte in HEX
set statusline=[%n]\ %F%y%m%r\ %=\ %b\ 0x%B\ \ \ %c,%l/%L\ \ %P

" OmniCppComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_MayCompleteDot = 0
let OmniCpp_MayCompleteArrow = 0
let OmniCpp_MayCompleteScope = 0
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]

" auto close options when exiting insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
set completeopt=menu,menuone


" MiniBufExplorer
let g:miniBufExplSortBy = "name"
let g:miniBufExplVSplit = 35
let g:miniBufExplSplitBelow = 0
let g:miniBufExplorerMoreThanOne=1
let g:miniBufExplCheckDupeBufs = 0

" NERD tree
let g:NERDTreeWinSize = 35

" Taglist or Tagbar
let g:Tlist_Auto_Open = 0
let g:Tlist_Show_One_File = 1
let g:Tlist_WinWidth = 40
let g:Tlist_Use_Right_Window = 1
let g:Tlist_Display_Prototype = 1
let g:Tlist_Use_Horiz_Window = 1
let g:Tlist_Close_On_Select = 1
let g:Tlist_Compact_Format = 1
let g:Tlist_WinHeight = 30
let g:Tlist_GainFocus_On_ToggleOpen = 1
let g:Tlist_Sort_Type = 'order'
let g:Tlist_Display_Tag_Scope = 1

let g:tagbar_left = 1
let g:tagbar_width = 100
let g:tagbar_show_visibility = 0
let g:tagbar_autoclose = 1
let g:tagbar_autofocus = 1
let g:tagbar_compact = 1
let g:tagbar_show_visibility = 0
let g:tagbar_sort = 0

hi TagbarSignature guifg=#c0c0c0 guibg=#000000 gui=none ctermfg=253 ctermbg=234

if filereadable('/Users/marc/ctags/ctags-5.8/ctags')
    let g:Tlist_Ctags_Cmd = '/Users/marc/ctags/ctags-5.8/ctags'
    let g:tagbar_ctags_bin = '/Users/marc/ctags/ctags-5.8/ctags'
endif

function TagsViewOpen()
    :TagbarOpen
    ":TlistOpen
endfunction

function TagsViewClose()
    :TagbarClose
    ":TlistClose
endfunction

let s:stayNormal = 0

" Insert/normal switching
function StartInsertIfModifiable()
  "let is_modified = getbufvar(bufnr('%'), '&modified')
  "echo bufname('%') is_modified
  " sl 1

  if getbufvar(bufnr('%'), '&modifiable') == 1
    if s:stayNormal == 0
      startinsert
    endif
  endif
endfunction

function StartNormal()
  let s:stayNormal = 1
  stopinsert
endfunction

function StartInsert()
  let s:stayNormal = 0
  startinsert
endfunction

autocmd CursorMoved * call StartInsertIfModifiable()
autocmd BufEnter * stopinsert
autocmd WinEnter * stopinsert
:noremap <SPACE> :call StartInsert()<CR>
:inoremap <Esc> <C-o>:call StartNormal()<CR>

" Jump to tag
:noremap <C-t> g<C-]>
:noremap! <C-t> <C-o>g<C-]>

" Jump to last tag
:noremap <C-r> <C-T>
:noremap! <C-r> <C-o><C-T>

" Open file (something like :e %:p:h)
let s:OpenWindow = 0

function ToggleOpenWindow()
    if s:OpenWindow == 0
        :call TagsViewClose()
        :CMiniBufExplorer
        :NERDTreeFind
        let s:OpenWindow = 1
    else 
        if s:OpenWindow == 1
            :call TagsViewClose()
            :NERDTreeClose
            :MiniBufExplorer
            let s:OpenWindow = 2
        else
            :NERDTreeClose
            :CMiniBufExplorer
            :call TagsViewOpen()
            let s:OpenWindow = 0
        endif
    endif
endfunction

" Toggle open buffer sidebar
:noremap <C-o> :call ToggleOpenWindow()<CR>
:noremap! <C-o> <C-o>:call ToggleOpenWindow()<CR>

" Save current file
:noremap <C-s> :w!<CR>
:noremap! <C-s> <C-o>:w!<CR>

" Window commands also for insert mode
:inoremap <C-w>q <C-o><C-w>q
:inoremap <C-w><Left> <C-o><C-w><Left>
:inoremap <C-w><Right> <C-o><C-w><Right>
:inoremap <C-w><Up> <C-o><C-w><Up>
:inoremap <C-w><Down> <C-o><C-w><Down>

" backspace in Visual mode deletes selection
:vnoremap <BS> d

" Undo changes
:noremap <C-z> u
:inoremap <C-z> <C-o>u

" Redo changes
:noremap <C-y> <C-r><CR>
:noremap! <C-y> <C-o><C-r>

" select text
:inoremap <S-Left> <C-o>vh
:nnoremap <S-Left> vh
:vnoremap <S-Left> h

:inoremap <S-Right> <C-o>vl
:nnoremap <S-Right> vl
:vnoremap <S-Right> l

:inoremap <S-Up> <C-o>vk
:nnoremap <S-Up> vk
:vnoremap <S-Up> k

:inoremap <S-Down> <C-o>vj
:nnoremap <S-Down> vj
:vnoremap <S-Down> j

" Shift text blocks
:vnoremap <Tab> >gv
:vnoremap <S-Tab> <gv

" Copy text
:noremap <C-c> "+y<CR>
:inoremap <C-c> <C-o>"+y

" Cut text
:noremap <C-x> "+x<CR>
:noremap! <C-x> <C-o>"+x

" Paste text
:vnoremap <C-v> <DEL>"+gP
:nnoremap <C-v> "+gP
:noremap! <C-v> <C-o>"+gP

" Enter block mode
:noremap <C-b> <C-v><CR>
:noremap! <C-b> <C-o><C-v>

" Find selected text
:vnoremap <C-f> "fy/<C-r>f<CR>
:vnoremap <M-f> "fy/<C-r>f<CR>NN
:inoremap <C-f> <C-o>/\C
:inoremap <C-n> <C-o>n
:inoremap <C-p> <C-o>N
:nnoremap <C-f> /\C

" Replace selected text
:vnoremap <C-h> "fy<C-o>:%s/<C-r>f/XXX/gc
