; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B29A926-2B8E-45DF-955C-1A469540F5C3}}
AppName=Platinum C++ Framework
AppVerName=Platinum C++ Framework (1.0.0)
AppPublisher=Platinum C++ Team
AppPublisherURL=http://www.pt-framework.org
AppSupportURL=http://www.pt-framework.org
AppUpdatesURL=http://www.pt-framework.org
DefaultDirName={pf}\Platinum-1.0.0\
DefaultGroupName=
DisableProgramGroupPage=no
OutputDir=.
OutputBaseFilename=Platinum-1.0.0-Setup
SetupIconFile=
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes


[Code]


[Run]

[UninstallRun]

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
;Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\deploy\vc10-x86-debug\include\*"; DestDir: "{app}\include\"; Flags: ignoreversion recursesubdirs
Source: "..\..\deploy\vc10-x86-debug\lib\*"; DestDir: "{app}\lib\vc10-x86-debug"; Flags: ignoreversion recursesubdirs
Source: "..\..\deploy\vc10-x86-release\lib\*"; DestDir: "{app}\lib\vc10-x86-release"; Flags: ignoreversion recursesubdirs


[Icons]

[Run]

