"""Conan 2 deployer: one relocatable ABI prefix plus jam/packages.jam."""

import os
import shutil


PACKAGE_DIR_MAP = {
    "zlib": "zlib",
    "libpng": "png",
    "libjpeg-turbo": "jpeg",
    "libjpeg": "jpeg",
    "freetype": "freetype",
    "openssl": "openssl",
}

PREFERRED_ORDER = ("zlib", "png", "jpeg", "freetype", "openssl")

LIB_SUFFIXES = (".lib", ".a", ".dylib")


def _prefix_name(conan_name):
    return PACKAGE_DIR_MAP.get(conan_name, conan_name)


def _is_lib(name):
    lower = name.lower()
    if lower.endswith(LIB_SUFFIXES):
        return True
    return ".so" in lower


def _is_deploy(name):
    lower = name.lower()
    if lower.endswith(".dll") or lower.endswith(".dylib"):
        return True
    return ".so" in lower


def _copy_tree(src, dst):
    if not os.path.isdir(src):
        return
    shutil.copytree(src, dst, dirs_exist_ok=True)


def _copy_files(src_dir, dst_dir, predicate):
    copied = []
    if not os.path.isdir(src_dir):
        return copied
    for name in sorted(os.listdir(src_dir)):
        src = os.path.join(src_dir, name)
        if not os.path.isfile(src):
            continue
        if predicate(name):
            os.makedirs(dst_dir, exist_ok=True)
            shutil.copy2(src, os.path.join(dst_dir, name))
            copied.append(name)
    return copied


def _rel_posix(path, root):
    rel = os.path.relpath(path, root)
    rel = rel.replace("\\", "/")
    if rel == "." or rel.startswith(".."):
        return None
    return rel


def _cpp_info(dep):
    cpp = dep.cpp_info
    aggregated = getattr(cpp, "aggregated_components", None)
    if aggregated is not None:
        cpp = aggregated()
    return cpp


def _host_items(conanfile):
    deps = conanfile.dependencies
    host = getattr(deps, "host", deps)
    return list(host.items())


def _direct_host_names(dep):
    names = []
    seen = set()
    deps = dep.dependencies
    direct_host = getattr(deps, "direct_host", None)
    if direct_host is not None:
        items = direct_host.items()
        filter_direct = False
    else:
        items = deps.items()
        filter_direct = True
    for require, other in items:
        if getattr(require, "build", False) or getattr(require, "test", False):
            continue
        if filter_direct and not getattr(require, "direct", True):
            continue
        name = _prefix_name(other.ref.name)
        if name not in seen:
            seen.add(name)
            names.append(name)
    return names


def _extra_includes(pkg_name, cpp, package_folder):
    extras = []
    seen = set()
    for includedir in cpp.includedirs or []:
        if os.path.isabs(includedir):
            rel = _rel_posix(includedir, package_folder)
        else:
            rel = includedir.replace("\\", "/").strip("/")
        if not rel or rel == "include":
            continue
        prefix_rel = pkg_name + "/" + rel
        if prefix_rel not in seen:
            seen.add(prefix_rel)
            extras.append(prefix_rel)
    return extras


def _jam_assign(name, values):
    if not values:
        return None
    if isinstance(values, str):
        values = [values]
    return "{} = {} ;".format(name, " ".join(values))


def _write_packages_jam(path, platform_id, packages):
    names = [p["name"] for p in packages]
    ordered = [n for n in PREFERRED_ORDER if n in names]
    ordered.extend(n for n in names if n not in ordered)

    by_name = {p["name"]: p for p in packages}
    lines = [
        "# Generated by conan/platform/deployer.py -- do not edit.",
        "if ! $(PLATFORM_PACKAGES_JAM_INCLUDED) {",
        "PLATFORM_PACKAGES_JAM_INCLUDED = true ;",
        "",
        "PLATFORM_SCHEMA  = 1 ;",
        "PLATFORM_ID      = {} ;".format(platform_id),
        "PLATFORM_LINKAGE = shared ;",
        "",
        "PLATFORM_PACKAGES = {} ;".format(" ".join(ordered)),
        "",
    ]

    for name in ordered:
        pkg = by_name[name]
        fields = [
            ("PLATFORM_PACKAGE_LIBS.{}".format(name), pkg["libs"]),
            ("PLATFORM_PACKAGE_DEPENDS.{}".format(name), pkg["depends"]),
            ("PLATFORM_PACKAGE_SYSLIBS.{}".format(name), pkg["syslibs"]),
            ("PLATFORM_PACKAGE_FRAMEWORKS.{}".format(name), pkg["frameworks"]),
            ("PLATFORM_PACKAGE_DEFINES.{}".format(name), pkg["defines"]),
            ("PLATFORM_PACKAGE_INCLUDES.{}".format(name), pkg["includes"]),
            ("PLATFORM_PACKAGE_DEPLOY.{}".format(name), pkg["deploy"]),
            ("PLATFORM_PACKAGE_VERSION.{}".format(name), [pkg["version"]] if pkg["version"] else []),
        ]
        written = False
        for var, values in fields:
            line = _jam_assign(var, values)
            if line:
                lines.append(line)
                written = True
        if written:
            lines.append("")

    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines))


def deploy(graph, output_folder, **kwargs):
    platform_id = os.environ.get("PLATFORM_ID", "").strip()
    if not platform_id:
        raise RuntimeError("PLATFORM_ID env var is required")

    conanfile = graph.root.conanfile
    os.makedirs(output_folder, exist_ok=True)

    packages = []
    exported = set()

    for _require, dep in _host_items(conanfile):
        package_folder = getattr(dep, "package_folder", None)
        if not package_folder or not os.path.isdir(package_folder):
            continue
        ref = dep.ref
        if ref.name == conanfile.name:
            continue

        pkg_name = _prefix_name(ref.name)
        dest = os.path.join(output_folder, pkg_name)

        _copy_tree(os.path.join(package_folder, "include"),
                   os.path.join(dest, "include"))

        _copy_files(os.path.join(package_folder, "lib"),
                    os.path.join(dest, "lib"),
                    _is_lib)

        deploy_files = _copy_files(os.path.join(package_folder, "bin"),
                                   os.path.join(dest, "bin"),
                                   _is_deploy)
        deploy_files.extend(_copy_files(os.path.join(package_folder, "lib"),
                                        os.path.join(dest, "bin"),
                                        lambda n: n.lower().endswith(".dll")))
        # Unique, stable order
        seen_deploy = set()
        unique_deploy = []
        for name in deploy_files:
            if name not in seen_deploy:
                seen_deploy.add(name)
                unique_deploy.append(name)
        deploy_files = unique_deploy

        has_include = os.path.isdir(os.path.join(dest, "include"))
        has_lib = os.path.isdir(os.path.join(dest, "lib")) and os.listdir(os.path.join(dest, "lib"))
        has_bin = os.path.isdir(os.path.join(dest, "bin")) and os.listdir(os.path.join(dest, "bin"))
        if not (has_include or has_lib or has_bin):
            if os.path.isdir(dest) and not os.listdir(dest):
                os.rmdir(dest)
            continue

        cpp = _cpp_info(dep)
        libs = [l for l in (cpp.libs or []) if l]
        syslibs = [l for l in (cpp.system_libs or []) if l]
        frameworks = [f for f in (cpp.frameworks or []) if f]
        defines = [d for d in (cpp.defines or []) if d]

        packages.append({
            "name": pkg_name,
            "version": str(ref.version),
            "libs": libs,
            "depends": [],
            "syslibs": syslibs,
            "frameworks": frameworks,
            "defines": defines,
            "includes": _extra_includes(pkg_name, cpp, package_folder),
            "deploy": deploy_files,
            "dep": dep,
        })
        exported.add(pkg_name)

    for pkg in packages:
        depends = [n for n in _direct_host_names(pkg["dep"]) if n in exported and n != pkg["name"]]
        pkg["depends"] = depends
        del pkg["dep"]

    if not packages:
        raise RuntimeError("deployer copied no host packages")

    _write_packages_jam(os.path.join(output_folder, "jam", "packages.jam"),
                        platform_id, packages)
