"""
JamDepsGenerator
================
Conan 2.x generator that produces a ``conan-deps.jam`` file containing
Jam variable definitions for all host dependencies.  The generated file
is meant to be included by Pt's Jamconfigure via ``--with-conan``.

Usage (in user's conanfile.py)
-------------------------------
    import sys, os
    sys.path.insert(0, "/path/to/pt/conan")
    from JamDepsGenerator import JamDepsGenerator

    class MyProject(ConanFile):
        def generate(self):
            JamDepsGenerator(self).generate()

Generated file format
---------------------
    PNG_INCLUDES = C:/path/to/include ;
    PNG_LIBDIR   = C:/path/to/lib ;
    PNG_LINKLIBS = [ FLinkLibs png16 ] ;

Jam variable naming convention
-------------------------------
Each dependency maps to a prefix:

    libpng        -> PNG
    zlib          -> ZLIB
    freetype      -> FREETYPE
    libjpeg       -> JPEG
    libjpeg-turbo -> JPEG
    openssl       -> SSL

Unknown packages are skipped unless a custom mapping is provided.
"""

import os

# Default Conan package-name -> Jam variable prefix mapping.
DEFAULT_PACKAGE_MAP = {
    "libpng":        "PNG",
    "zlib":          "ZLIB",
    "freetype":      "FREETYPE",
    "libjpeg":       "JPEG",
    "libjpeg-turbo": "JPEG",
    "openssl":       "SSL",
}

OUTPUT_FILENAME = "conan-deps.jam"


def _jam_path(path):
    """Convert a filesystem path to a Jam-safe string."""
    p = path.replace("\\", "/")
    if " " in p:
        return '"{}"'.format(p)
    return p


def _jam_paths(paths):
    return " ".join(_jam_path(p) for p in paths if p)


class JamDepsGenerator:
    """Generates conan-deps.jam from all host dependencies."""

    def __init__(self, conanfile, package_map=None):
        self._conanfile = conanfile
        self._package_map = package_map if package_map is not None else DEFAULT_PACKAGE_MAP

    def generate(self):
        content = self._build_content()
        output_path = os.path.join(self._conanfile.generators_folder, OUTPUT_FILENAME)
        with open(output_path, "w") as f:
            f.write(content)
        self._conanfile.output.info("JamDepsGenerator: wrote {}".format(output_path))

    def _build_content(self):
        lines = [
            "# Generated by JamDepsGenerator -- do not edit manually.",
            "# Re-generate by running:  conan install .",
            "",
        ]

        for req, dep in self._conanfile.dependencies.host.items():
            name = dep.ref.name
            prefix = self._package_map.get(name)
            if not prefix:
                continue

            cpp_info = dep.cpp_info.aggregated_components()

            include_dirs = [d for d in (cpp_info.includedirs or []) if d]
            lib_dirs     = [d for d in (cpp_info.libdirs     or []) if d]
            libs         = [l for l in (cpp_info.libs        or []) if l]
            defines      = [d for d in (cpp_info.defines     or []) if d]
            cxxflags     = [f for f in (cpp_info.cxxflags    or []) if f]

            lines.append("# {} ({})".format(prefix, name))

            if include_dirs:
                lines.append("{}_INCLUDES = {} ;".format(
                    prefix, _jam_paths(include_dirs)))

            if lib_dirs:
                # Pass the first libdir; Jam's CheckDependency* uses it
                # as a search path hint.
                lines.append("{}_LIBDIR = {} ;".format(
                    prefix, _jam_path(lib_dirs[0])))

            if libs:
                # Emit as a FLinkLibs call so Jam applies platform-specific
                # name formatting (e.g. png16.lib on MSVC, -lpng16 on GCC).
                lines.append("{}_LINKLIBS = [ FLinkLibs {} ] ;".format(
                    prefix, " ".join(libs)))

            cflags_parts = []
            if defines:
                cflags_parts.extend("-D{}".format(d) for d in defines)
            if cxxflags:
                cflags_parts.extend(cxxflags)
            if cflags_parts:
                lines.append("{}_C++FLAGS = {} ;".format(
                    prefix, " ".join(cflags_parts)))

            lines.append("")

        return "\n".join(lines)
