/* Copyright (C) 2015 Marc Boris Duerner 

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef PT_COSMO_API_H
#define PT_COSMO_API_H

#include <Pt/Api.h>

#define PT_COSMO_VERSION_MAJOR PT_VERSION_MAJOR
#define PT_COSMO_VERSION_MINOR PT_VERSION_MINOR
#define PT_COSMO_VERSION_REVISION PT_VERSION_REVISION
#define PT_COSMO_VERSION_PRERELEASE PT_VERSION_PRERELEASE

#if defined(PT_COSMO_API_EXPORT)
#    define PT_COSMO_API PT_EXPORT
#  else
#    define PT_COSMO_API PT_IMPORT
#  endif

namespace Pt {

/** @brief %Cosmo Component Model.

    The Cosmo component model allows to assemble programs from several
    components. Each component implements one or more interfaces and may
    depend on one or more interfaces of other components. 
    The component manager of the Cosmo application is used to create
    components and to resolve dependencies between them. In order to create a
    component, the according component plugin has to be impemented.
*/
namespace Cosmo {

} // namespace

} // namespace
 
#endif // include guard
