/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_AUTO_PTR_H
#define COSMO_AUTO_PTR_H

#include <Pt/Cosmo/Api.h>

namespace Pt {

namespace Cosmo {

/** @internal @brief Auto pointer implemantation.
*/
template<typename T>
class AutoPtrImpl
{
  public:
    AutoPtrImpl(T* ptr)
    : _ptr(ptr)
    { }

    virtual ~AutoPtrImpl()
    { }

    void reset(T* ptr = 0)
    {
      if(_ptr)
        onReset(_ptr);
      
      _ptr = ptr;
    }

    void destroy()
    {
      onDestroy();
    }

    T* get()
    {
      return _ptr;
    }

  protected:
    virtual void onReset(T* ptr) = 0;

    virtual void onDestroy() = 0;

  private:
    T* _ptr;
};

/** @internal @brief Auto pointer implemantation.
*/
template <typename Y, typename B, typename D>
class AutoPtrData : public AutoPtrImpl<B>
{
  public:
    AutoPtrData(Y* res, D del)
    : AutoPtrImpl<B>(res)
    , _del(del)
    { }

  protected:
    virtual void onReset(B* ptr)
    {
      _del( static_cast<Y*>(ptr) );
    }

    virtual void onDestroy()
    {
      delete this;
    }

  private:
    D  _del;
};

/** @internal @brief Auto pointer reference.
*/
template<typename T>
struct AutoPtrRef 
{
  AutoPtrImpl<T>* ptr;
    
  explicit AutoPtrRef(AutoPtrImpl<T>* ap)
  : ptr(ap)
  { }
};

/** @brief Owning smart pointer.

    Manages the lifetime of a dynamically allocated object using a
    configurable deleter. Supports move semantics but not copying.

    @ingroup Cosmo-Memory
*/
template<typename T>
class AutoPtr
{
  private:
    template <typename Y>
    class DefaultDelete
    {
      public:
        void operator()(Y* res)
        {
          delete res;
        }
    };

    public:
        typedef T element_type;

    public:
        //! @brief Default constructor.
        AutoPtr()
        : _ptr(0)
        { }

        //! @brief Constructor.
        template <typename Y>
        explicit AutoPtr(Y* ptr)
        : _ptr(0)
        {
            DefaultDelete<Y> deleter;
            _ptr = new AutoPtrData<Y, T, DefaultDelete<Y> >(ptr, deleter);
        }

        //! @brief Constructor.
        template <typename Y, typename Deleter>
        AutoPtr(Y* ptr, Deleter deleter)
        : _ptr(0)
        { 
            _ptr = new AutoPtrData<Y, T, Deleter>(ptr, deleter);
        }

        //! @brief Copy constructor (C++03 move via AutoPtrRef).
        AutoPtr(AutoPtrRef<T> rhs)
        : _ptr(rhs.ptr) 
        { }

        //! @brief Move constructor.
        AutoPtr(AutoPtr&& other)
        : _ptr(other._ptr)
        { other._ptr = 0; }

        //! @brief Destructor.
        ~AutoPtr()
        { 
            reset(); 
        }

        //! @brief Move assignment operator.
        AutoPtr& operator=(AutoPtr&& other)
        {
            if( this != &other )
            {
                reset();
                _ptr = other._ptr;
                other._ptr = 0;
            }
            return *this;
        }

        //! @brief Assignment operator (C++03 move via AutoPtrRef).
        AutoPtr& operator= (AutoPtrRef<T> rhs)
        {           
            this->reset();
            _ptr = rhs.ptr;
            return *this;
        }

        //! @brief Conversion operator used for assignments.
        template<class Y>
        operator AutoPtrRef<Y>()
        {
            AutoPtrImpl<Y>* tmp = _ptr;
            _ptr = 0;
            return AutoPtrRef<Y>(tmp);
        }

        //! @brief Access value.
        T* get() const 
        {
            return _ptr ? _ptr->get() : 0;
        }

        //! @brief Access value.
        T& operator*() const 
        {
            return *_ptr->get();
        }

        //! @brief Access value.
        T* operator->() const 
        {
            return _ptr->get();
        }

        //! @brief Returns true if nullptr.
        bool operator !() const 
        {
            return _ptr == 0;
        }
        
        //! @brief Returns true if valid pointer.
        operator bool() const
        { 
            return _ptr != 0; 
        }

        //! @brief Release ownership.
        T* release() 
        {
            if( ! _ptr )
              return 0;

            T* tmp = _ptr->get();
            _ptr->destroy();
            _ptr = 0;

            return tmp;
        }

        //! @brief Reset value.
        void reset()
        {
            if(_ptr)
            {
                _ptr->reset();
                _ptr->destroy();
                _ptr = 0;
            }
        }

        //! @brief Reset value.
        template <typename Y>
        void reset(Y* ptr)
        {
            if( ! ptr )
            {
              reset();
              return;
            }

            if(_ptr)
            {
                _ptr->reset(ptr);
            }
            else
            {
                DefaultDelete<Y> deleter;
                _ptr = new AutoPtrData<Y, T, DefaultDelete<Y> >(ptr, deleter);
            }
        }

    private:
        AutoPtr(AutoPtr &p);

        AutoPtr& operator =(AutoPtr& p);

    private:
        AutoPtrImpl<T>* _ptr;
};

/** @brief Move to other instance.

    @related AutoPtr
*/
template <typename T>
AutoPtr<T> move(AutoPtr<T>& p)
{
    return AutoPtr<T>( AutoPtrRef<T>(p) );
}

/** @brief Equality comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator==(const AutoPtr<T>& a, const AutoPtr<Y>& b)
{ return a.get() == b.get(); }

/** @brief Equality comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator==(const AutoPtr<T>& a, const Y* b)
{ return a.get() == b; }

/** @brief Equality comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator!=(const AutoPtr<T>& a, const AutoPtr<Y>& b)
{ return a.get() != b.get(); }

/** @brief Equality comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator!=(const AutoPtr<T>& a, const Y* b)
{ return a.get() != b; }

/** @brief Less-than comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator<(const AutoPtr<T>& a, const AutoPtr<Y>& b)
{ return a.get() < b.get(); }

/** @brief Less-than comparison operator.

    @related AutoPtr
*/
template <typename T, typename Y>
bool operator<(const AutoPtr<T>& a, const Y* b)
{ return a.get() < b; }

} // namespace Cosmo

} // namespace Pt

#endif // include guard
