/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_AUTO_RELEASE_POOL_H
#define COSMO_AUTO_RELEASE_POOL_H

#include <Pt/Cosmo/IAutoReleasePool.h>

namespace Pt {

namespace Cosmo {

/** @brief Auto-release pool implementation.

    Concrete pool that maintains a singly-linked list of
    %AutoReleasable objects. All attached objects are released
    when the pool is destroyed or reset.

    @ingroup Cosmo-Memory
*/
class AutoReleasePool : public IAutoReleasePool
{
  public:
    AutoReleasePool()
    : _head(0)
    { }

    virtual ~AutoReleasePool()
    {
      while( _head )
        _head->reset();
    }

    void reset()
    {
      while( _head )
        _head->reset();
    }

  protected:
    virtual void onAttachReleasable(AutoReleasable& ar) override
    {
      ar._next = _head;
      _head = &ar;
    }

    virtual void onDetachReleasable(AutoReleasable& ar) override
    {
      if(_head == &ar)
      {
        _head = _head->_next;
        ar._next = 0;
        return;
      }

      AutoReleasable* prev = _head;
      AutoReleasable* node = _head->_next;

      while(node)
      {
        if(node == &ar)
        {
          prev->_next = node->_next;
          ar._next = 0;
          break;
        }

        prev = node;
        node = node->_next;
      }
    }

  private:
    AutoReleasePool(const AutoReleasePool& other) = delete;

    AutoReleasePool& operator=(const AutoReleasePool& other) = delete;

  private:
    AutoReleasable* _head;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
