/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_BUFFER_H
#define COSMO_BUFFER_H

#include <Pt/Cosmo/Api.h>
#include <vector>

namespace Pt {

 namespace Cosmo {

/** @brief Buffer interface.

    Abstract interface for a managed byte buffer supporting
    assign, append, and clear operations.

    @ingroup Cosmo-Memory
*/
class IBuffer
{
  public:
    virtual ~IBuffer()
    { }

    bool isEmpty()
    {
      return size() == 0;
    }

    unsigned size() const
    {
      return onGetSize();
    }

    const char* data() const
    {
      return onGetData();
    }

    void assign(const char* data, unsigned n)
    {
      return onAssignData(data, n);
    }

    void append(const char* data, unsigned n)
    {
      return onAppendData(data, n);
    }

    void clear()
    {
      assign(0, 0);
    }

  protected:
    virtual unsigned onGetSize() const = 0;

    virtual const char* onGetData() const = 0;

    virtual void onAppendData(const char* data, unsigned n) = 0;

    virtual void onAssignData(const char* data, unsigned n) = 0;
};


/** @brief Default buffer implementation.

    Implements %IBuffer backed by a std::vector.

    @ingroup Cosmo-Memory
*/
class Buffer : public IBuffer
{
  public:
    Buffer()
    { }

    Buffer(const char* data, unsigned n) 
    : _data(data, data + n)
    { }

  protected:
    virtual unsigned onGetSize() const override
    {
      return static_cast<unsigned>( _data.size() );
    }

    virtual const char* onGetData() const
    {
      return &_data[0];
    }

    virtual void onAppendData(const char* data, unsigned n) override
    {
      _data.insert(_data.end(), data, data + n);
    }

    virtual void onAssignData(const char* data, unsigned n) override
    {
      _data.insert(_data.end(), data, data + n);
    }

  private:
    std::vector<char> _data;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
