/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_H
#define COSMO_COMPONENT_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/Enumerable.h>

#include <string>
#include <vector>

namespace Pt {

namespace Cosmo {

class IComponentType;
class IComponentDeclaration;

/** @brief Component base class.

    All Cosmo components derive from %Component. A component exposes its
    capabilities through interfaces derived from %IUnknown that are
    discovered via queryInterface().

    @ingroup Cosmo-Component
*/
class Component
{
  public:
    /** @brief Constructor.
    */
	  Component();

    /** @brief No copy constructor.
    */
    Component(const Component&) = delete;

    /** @brief Destructor.
    */
	  virtual ~Component()
	  {}

    /** @brief No copy assignment.
    */
    Component& operator=(const Component&) = delete;

    /** @brief Initializes the component.

        Called by the component plugin after creation. Assigns the
        component type and declaration, then invokes onInitialize().

        @param type The component type providing interface metadata.
        @param decl The instance declaration from the manifest.
    */
    void init(const IComponentType* type,
              const IComponentDeclaration* decl);
   
    /** @brief Returns true if the given feature ID is implemented.

        @param featureId The feature ID to check.
    */
    bool hasFeatureId(const char* featureId) const;
    
    /** @brief Returns the class ID.
    */
    const char* classId() const;

    /** @brief Returns the interface or null if not available.
    */
    template <typename I>
    I* queryInterface();

  protected:
    /** @brief Called when the component is initialized.

        Override to perform setup that requires access to the
        instance declaration.

        @param decl The instance declaration from the manifest.
    */
    virtual void onInitialize(const IComponentDeclaration& decl)
    { }

  private:
    const IComponentType*        _type;
    const IComponentDeclaration* _decl;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/Component.tpp>

#include <Pt/Cosmo/IActivate.h>
#include <Pt/Cosmo/IConnect.h>

#endif // include guard
