/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_MANAGER_H
#define COSMO_COMPONENT_MANAGER_H

#include <Pt/Cosmo/Component.h>
#include <Pt/Cosmo/ComponentPlugin.h>
#include <Pt/Cosmo/IComponentManager.h>
#include <Pt/Cosmo/Enumerable.h>

#include <string>

namespace Pt {

namespace Cosmo {

class ComponentInfo;
class IComponentInfo;

/** @brief Default component manager.

    Concrete implementation of %IComponentManager. Manages plugin
    registration, manifest import, dependency resolution, and the
    component load/unload lifecycle.

    @ingroup Cosmo-Component
*/
class PT_COSMO_API ComponentManager : public Component  
{  
  public:
    template <typename I>
    I* getInterface();

  public:
    /** @brief Constructor.
    */
    ComponentManager();

    /** @brief Destructor.
    */
    ~ComponentManager();

    /** @brief Set modules search directory.
    */
    void setModulesDir(const std::string& dir);

    /** @brief Imports all components from manifest.
    */
    void importComponents(const std::string& manifest);

    /** @brief Registers component.
    */
    void registerComponent(IComponentPlugin& plugin,
                           const std::string& require,
                           const std::string& instanceId);

    /** @brief Loads all registered components.
    */
    void load();

    /** @brief Loads registered component.
    */
    void load(const std::string& instanceId);

    /** @brief Unloads a component plugin.
    */
    void unload(IComponentPlugin& plugin);

    /** @brief Unloads a component by instance ID.
    */
    void unload(const std::string& instanceId);

    /** @brief Enumerates all components.
    */
    const IEnumerable<ComponentInfo>& components() const;

  private:
    class ComponentManagerPlugin*  _plugin;
    class ComponentManagerImpl*    _impl;
};

/** @internal @brief ComponentManager component factory.
*/
class ComponentManagerFactory
{
  public:
    /** @brief Constructor.
    */
    explicit ComponentManagerFactory(ComponentManager& cm)
    : _cm(&cm)
    {}

    Component* create()
    { return _cm; }

    void destroy(Component* instance)
    { }

  private:
    ComponentManager* _cm;
};

/** @internal @brief ComponentManager component plugin.
*/
class ComponentManagerPlugin : public ComponentPlugin<ComponentManager, 
                                                      ComponentManagerFactory>
{
  public:
    static const char* FeatureId()
    { return "Cosmo.ComponentManager"; }

    static const char* ClassId()
    { return "Cosmo.ComponentManager"; }

    static const char* Info()
    { return "Cosmo.Default"; }

  public:
    ComponentManagerPlugin(ComponentManager& cm);
};

} // namespace Cosmo

} // namespace Pt

#endif
