/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#include <Pt/Cosmo/Component.h>
#include <Pt/Cosmo/IComponentManager.h>

namespace Pt {

namespace Cosmo {

template <typename T, typename Factory>
class ComponentPlugin<T, Factory>::IThunk
{
  public:
    virtual ~IThunk()
    {}

    virtual IUnknown* get(Component& base) const = 0;
};


template <typename T, typename Factory>
template <typename I>
class ComponentPlugin<T, Factory>::GetAggregated : public IThunk
{
  typedef I* (T::*Func)();

  public:
    GetAggregated(Func f)
    : _f(f)
    {}

    virtual IUnknown* get(Component& base) const
    {
      T& object = static_cast<T&>(base);
      return (object.*_f)();
    }

  private:
    Func _f;
};


template <typename T, typename Factory>
template <typename I>
class ComponentPlugin<T, Factory>::GetInherited : public IThunk
{
  public:
    GetInherited()
    {}

    virtual IUnknown* get(Component& base) const
    {
      T& object = static_cast<T&>(base);
      return static_cast<I*>(&object);
    }
};


template <typename T, typename Factory>
ComponentPlugin<T, Factory>::ComponentPlugin(const char* featureId,
                                             const char* info, ComponentMode mode,
                                             const Factory& factory)
: _factory(factory)
, _classId(featureId)
, _info(info)
, _mode(mode)
, _featureIdsEnum(_pool, _featureIds)
, _dependenciesEnum(_pool, _dependencies)
{
  registerFeatureId(featureId);
}


template <typename T, typename Factory>
ComponentPlugin<T, Factory>::ComponentPlugin(const char* featureId, const char* classId,
                                             const char* info, ComponentMode mode,
                                             const Factory& factory)
: _factory(factory)
, _classId(classId)
, _info(info)
, _mode(mode)
, _featureIdsEnum(_pool, _featureIds)
, _dependenciesEnum(_pool, _dependencies)
{
  registerFeatureId(featureId);
}


template <typename T, typename Factory>
ComponentPlugin<T, Factory>::~ComponentPlugin()
{
  while( ! _componentManager.empty() )
  {
    auto it = _componentManager.begin();
    IComponentManager* cm = it->first;
    cm->unload(*this);
  }
 
  typedef typename ThunkMap::iterator ThunkIterator;
  for(ThunkIterator it = _thunks.begin(); it != _thunks.end(); ++it)
  {
    delete it->second;
  }
}


template <typename T, typename Factory>
template <typename I>
void ComponentPlugin<T, Factory>::registerInterface()
{
  const std::type_info& ti = typeid(I);

  typedef typename ThunkMap::iterator ThunkIterator;
  ThunkIterator it = _thunks.find(ti);
  if( it != _thunks.end() )
  {
    delete it->second;
    _thunks.erase(it);
  }

  _thunks[ti] = new GetInherited<I>();
}


template <typename T, typename Factory>
template <typename I>
void ComponentPlugin<T, Factory>::registerInterface( I* (T::*getter)() )
{
  const std::type_info& ti = typeid(I);

  typedef typename ThunkMap::iterator ThunkIterator;
  ThunkIterator it = _thunks.find(ti);
  if( it != _thunks.end() )
  {
    delete it->second;
    _thunks.erase(it);
  }

  _thunks[ti] = new GetAggregated<I>(getter);
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::registerDependency(const char* featureId)
{
  _dependencies.push_back(featureId);
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::registerFeatureId(const char* featureId)
{
  if( hasFeatureId(featureId) )
    return;

  _featureIds.push_back(featureId);
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::onAttach(IComponentManager& cm, const std::string& instance)
{
  _componentManager.insert( std::make_pair(&cm, instance) );
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::onDetach(IComponentManager& cm, const std::string& instance)
{
  auto range = _componentManager.equal_range(&cm);
  for( auto it = range.first; it != range.second; ++it  )
  {
    if( it->second == instance )
    {
      _componentManager.erase(it);
      break;
    }
  }
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::onDetach(IComponentManager& cm)
{
  _componentManager.erase(&cm);
}


template <typename T, typename Factory>
const IEnumerable<const char*>& ComponentPlugin<T, Factory>::onGetDependencies() const
{
  return _dependenciesEnum;
}


template <typename T, typename Factory>
ComponentMode ComponentPlugin<T, Factory>::onGetMode() const
{
  return _mode;
}


template <typename T, typename Factory>
bool ComponentPlugin<T, Factory>::onHasFeatureId(const char* featureId) const
{
  for(const std::string& fid : _featureIds)
  {
    if(fid == featureId)
      return true;
  }

  return false;
}


template <typename T, typename Factory>
const IEnumerable<const char*>& ComponentPlugin<T, Factory>::onGetFeatureIds() const
{
  return _featureIdsEnum;
}


template <typename T, typename Factory>
const char* ComponentPlugin<T, Factory>::onGetClassId() const
{
  return _classId.c_str();
}


template <typename T, typename Factory>
const char* ComponentPlugin<T, Factory>::onGetInfo() const
{
  return _info.c_str();
}


template <typename T, typename Factory>
Component* ComponentPlugin<T, Factory>::onCreate()
{ 
  return _factory.create();
}


template <typename T, typename Factory>
void ComponentPlugin<T, Factory>::onDestroy(Component* instance)
{ 
  _factory.destroy(instance);
}


template <typename T, typename Factory>
bool ComponentPlugin<T, Factory>::onHasInterface(const std::type_info& ti) const
{ 
  return _thunks.find(ti) != _thunks.end();
}


template <typename T, typename Factory>
IUnknown* ComponentPlugin<T, Factory>::onQueryInterface(Component& c, 
                                                        const std::type_info& ti) const
{ 
  typedef typename ThunkMap::const_iterator ThunkIterator;
  ThunkIterator it = _thunks.find(ti);
  if( it == _thunks.end() )
    return 0; 

  return it->second->get(c);
}

} // namespace Cosmo

} // namespace Pt
