/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_PLUGIN_H
#define COSMO_COMPONENT_PLUGIN_H

#include <Pt/Cosmo/ComponentMode.h>
#include <Pt/Cosmo/Enumerable.h>
#include <Pt/Cosmo/AutoReleasePool.h>
#include <Pt/Cosmo/IComponentPlugin.h>

#include <string>
#include <vector>
#include <map>
#include <typeindex>
#include <typeinfo>

namespace Pt {

namespace Cosmo {

class Component;
class IComponentManager;

/** @internal @brief Default component factory.
*/
template <typename T>
class ComponentFactory
{
  public:
    /** @brief Constructor.
    */
    ComponentFactory()
    {}

    /** @brief Creates a component instance.
    */
    Component* create()
    {
      return new T();
    }

    /** @brief Destroys a component instance.
    */
    void destroy(Component* instance)
    {
      delete instance;
    }
};

/** @internal @brief From Reference component factory.
*/
template <typename T>
class FromReference
{
  public:
    explicit FromReference(T& instance)
    : _instance(&instance)
    {}

    Cosmo::Component* create()
    { return _instance; }

    void destroy(Cosmo::Component* /*instance*/)
    {}

  private:
    T* _instance;
};

/** @brief Default component plugin.

    Implements the %IComponentPlugin interface for a concrete component
    class T. Provides registration of interfaces, dependencies, and
    feature IDs. Uses a configurable factory (default: %ComponentFactory)
    to create and destroy component instances.

    @ingroup Cosmo-Component
*/
template <typename T, typename Factory = ComponentFactory<T> >
class ComponentPlugin : public IComponentPlugin
{
  public:
    class IdListEnumeration : public IEnumeration<const char*>
    {
      public:
        IdListEnumeration(const std::vector<std::string>& list)
        : _list(list)
        , _it( list.begin() )
        { }

      protected:
        virtual bool onIsValid() const override
        {
          return _it != _list.end();
        }

        virtual void onAdvance() override
        {
          ++_it;
        }

        virtual const char* onGet() const override
        {
          return _it->c_str();
        }

      private:
        const std::vector<std::string>&                   _list;
        typename std::vector<std::string>::const_iterator _it;
    };

    class IdList : public IEnumerable<const char*>
    {
      public:
        IdList(IAutoReleasePool& pool,
               const std::vector<std::string>& strings)
        : _pool(pool)
        , _strings(strings)
        { }

      protected:
        Cosmo::Enumerator<const char*> onEnumerate() const
        {
          IdListEnumeration* e = new IdListEnumeration(_strings);
          return Cosmo::Enumerator<const char*>(_pool, e);
        }

      private:
        IAutoReleasePool&                _pool;
        const std::vector<std::string>&  _strings;
    };

  public:
    ComponentPlugin(const char* featureId, const char* info,
                    ComponentMode mode = ComponentMode::None,
                    const Factory& factory = ComponentFactory<T>());

    /** @brief Constructor.

        The @a featureId is the primary feature ID used to create the component
        from application code, @a info is the implementation info string and
        the @a mode flags indicate various operation modes such as auto-start.
    */
    ComponentPlugin(const char* featureId, const char* classId, const char* info,
                    ComponentMode mode = ComponentMode::None,
                    const Factory& factory = ComponentFactory<T>());

    /** @brief Destructor.
    */
    ~ComponentPlugin();

    /** @brief Registers a component interface.
    */
    template <typename I>
    void registerInterface();

    /** @brief Registers a component interface.
    */
    template <typename I>
    void registerInterface( I* (T::*getter)() );

    /** @brief Registers the dependency to another component.
    */
    void registerDependency(const char* featureId);

    /** @brief Registers a feature ID.
    */
    void registerFeatureId(const char* featureId);

  protected:
    // inherit docs
    virtual bool onHasFeatureId(const char* featureId) const override;

    // inherit docs
    virtual const IEnumerable<const char*>& onGetFeatureIds() const override;

    // inherit docs
    virtual const char* onGetClassId() const override;

    // inherit docs
    bool onHasInterface(const std::type_info& ti) const override;

    // inherit docs
    virtual IUnknown* onQueryInterface(Component& c,
                                       const std::type_info& ti) const override;

  protected:
    // inherit docs
    virtual void onAttach(IComponentManager& cm,
                          const std::string& instance) override;

    // inherit docs
    virtual void onDetach(IComponentManager& cm,
                          const std::string& instance) override;

    // inherit docs
    virtual void onDetach(IComponentManager& cm) override;

    // inherit docs
    virtual const IEnumerable<const char*>& onGetDependencies() const override;

    // inherit docs
    virtual ComponentMode onGetMode() const override;

    // inherit docs
    virtual const char* onGetInfo() const override;

    // inherit docs
    virtual Component* onCreate() override;

    // inherit docs
    virtual void onDestroy(Component* instance) override;

  private:
    class IThunk;

    template <typename I>
    class GetAggregated;

    template <typename I>
    class GetInherited;

    typedef std::map<std::type_index, IThunk*> ThunkMap;
    ThunkMap _thunks;

    Factory                   _factory;
    std::string               _classId;
    std::vector<std::string>  _featureIds;
    std::string               _info;
    ComponentMode             _mode;
    std::vector<std::string>  _dependencies;

    std::multimap<IComponentManager*,
                  std::string>        _componentManager;

    AutoReleasePool _pool;
    IdList          _featureIdsEnum;
    IdList          _dependenciesEnum;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/ComponentPlugin.tpp>

#endif
