/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_INFO_H
#define COSMO_COMPONENT_INFO_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IComponentPlugin.h>
#include <Pt/Cosmo/IComponentDeclaration.h>
#include <Pt/Cosmo/IComponentStatus.h>
#include <Pt/Cosmo/IEnumerable.h>

#include <string>

namespace Pt {

namespace Cosmo {

class IDependencyInfo;

/** @brief Component information holder.

    Aggregates the plugin, instance declaration, and status for a
    registered component. Used by %IComponentManager to enumerate
    component metadata.

    @ingroup Cosmo-Component
*/
class ComponentInfo
{
  public:
    /** @brief Constructor.

        @param plugin The component plugin.
        @param decl The instance declaration.
        @param status The component status.
    */
    ComponentInfo(IComponentPlugin* plugin,
                  IComponentDeclaration* decl,
                  IComponentStatus* status)
    : _plugin(plugin)
    , _decl(decl)
    , _status(status)
    { }

    /** @brief No copy constructor.
    */
    ComponentInfo(const ComponentInfo&) = delete;

    /** @brief Destructor.
    */
    virtual ~ComponentInfo()
    { }

    /** @brief No copy assignment.
    */
    ComponentInfo& operator=(const ComponentInfo&) = delete;

    /** @brief Reassigns the component information.

        @param plugin The component plugin.
        @param decl The instance declaration.
        @param status The component status.
    */
    void assign(IComponentPlugin* plugin,
                IComponentDeclaration* decl,
                IComponentStatus* status)
    {
      _plugin = plugin;
      _decl = decl;
      _status = status;
    }

    /** @brief Returns the plugin.
    */
    const IComponentPlugin* plugin() const
    {
      return _plugin;
    }

    /** @brief Returns the instance declaration.
    */
    const IComponentDeclaration* declaration() const
    {
      return _decl;
    }

    /** @brief Returns the component status.
    */
    const IComponentStatus* status() const
    {
      return _status;
    }

    /** @brief Returns true if interface is available.
    */
    template<typename I>
    bool hasInterface() const
    {
      return _plugin->hasInterface<I>();
    }

    /** @brief Returns the component mode.
    */
    ComponentMode mode() const
    {
      return _plugin->mode();
    }

    /** @brief Returns true if feature ID is implemented.
    */
    bool hasFeatureId(const char* featureId) const
    {
      return _plugin->hasFeatureId(featureId);
    }

    /** @brief Returns the implemented feature IDs.
    */
    const IEnumerable<const char*>& featureIds() const
    {
      return _plugin->featureIds();
    }

    /** @brief Returns the class ID.
    */
    const char* classId() const
    {
      return _plugin->classId();
    }

    /** @brief Returns the info text.
    */
    const char* info() const
    {
      return _plugin->info();
    }

    /** @brief Returns the instance ID.
    */
    const char* instanceId() const
    {
      return _decl->instanceId();
    }

    /** @brief Returns info about the dependencies.
    */
    const IEnumerable<IDependencyInfo>& dependencies() const
    {
      return _status->dependencies();
    }

  private:
    IComponentPlugin*      _plugin;
    IComponentDeclaration* _decl;
    IComponentStatus*      _status;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
