/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_ENUMERABLE_H
#define COSMO_ENUMERABLE_H

#include <Pt/Cosmo/IEnumerable.h>
#include <Pt/Cosmo/IAutoReleasePool.h>

namespace Pt {

namespace Cosmo {

/** @brief Makes any standard C++ container enumerable.

    Adapts a standard container to the %IEnumerable interface so it
    can be iterated using the Cosmo enumeration mechanism.

    @ingroup Cosmo-Enumeration
*/
template <typename Container, class T = typename Container::value_type>
class BasicEnumerable : public IEnumerable<T>
{
  public:
    class Enumeration : public IEnumeration<T>
    {
      typedef typename IEnumeration<T>::Reference Reference;

      public:
        Enumeration(const Container& container)
        : _container(container)
        , _it( container.begin() )
        { }

      protected:
        virtual bool onIsValid() const override
        {
          return _it != _container.end();
        }

        virtual void onAdvance() override
        {
          ++_it;
        }

        virtual Reference onGet() const override
        {
          return *_it;
        }

      private:
        const Container&                   _container;
        typename Container::const_iterator _it;
    };

  public:
    BasicEnumerable(IAutoReleasePool& pool, 
                    Container& container)
    : _pool(&pool)
    , _container(&container)
    { }
 
    BasicEnumerable(const BasicEnumerable& other) = delete;

    virtual ~BasicEnumerable()
    { }

    BasicEnumerable& operator=(const BasicEnumerable& other) = delete;

    void set(IAutoReleasePool& pool, Container& container)
    {
      _pool = &pool;
      _container = &container;
    }

  protected:
    virtual Cosmo::Enumerator<T> onEnumerate() const override
    {
      Enumeration* e = new Enumeration(*_container);
      return Cosmo::Enumerator<T>(*_pool, e);
    }

  private:
    IAutoReleasePool* _pool;
    Container*        _container;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
