/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_ACTIVATOR_INTERFACE_H
#define COSMO_ACTIVATOR_INTERFACE_H

#include <Pt/Cosmo/Api.h>

#include <string>
#include <stdexcept>

namespace Pt {

namespace Cosmo {

class Component;

/** @brief Dependency resolver.

    Passed to %IActivate::onActivate() to resolve required dependencies
    by feature ID. Use get() when the dependency is mandatory (throws
    on failure) or query() when it may legitimately be absent.

    @ingroup Cosmo-Activation
*/
class IActivator
{
  public:
    /** @brief Constructor.
    */
    IActivator()
    {
    }

    /** @brief Destructor.
    */
    virtual ~IActivator()
    {}

    /** @brief Returns the component by feature ID or throws.

        @param featureId Feature ID of the required component.
    */  
    Component* get(const std::string& featureId) const;

    /** @brief Returns the interface from a component or throws.

        @param id Feature ID of the required component.
    */  
    template<typename I>
    I* get(const std::string& id) const;

    /** @brief Returns the component by feature ID or null.

        @param featureId Feature ID of the component.
    */  
    Component* query(const std::string& featureId) const;

    /** @brief Returns the interface from a component or null.

        @param id Feature ID of the component.
    */  
    template<typename I>
    I* query(const std::string& id) const;

  protected:
    /** @brief Gets the component by feature ID or null if not available.
    */  
    virtual Component* onQuery(const std::string& featureId) const = 0;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/Component.h>

namespace Pt {

namespace Cosmo {

inline Component* IActivator::get(const std::string& featureId) const
{
  Component* c = onQuery(featureId);
  if( ! c )
    throw std::invalid_argument(featureId);

  return c;
}


template<typename I>
I* IActivator::get(const std::string& featureId) const
{
  Component* c = get(featureId);
  
  I* i = c->queryInterface<I>();
  if( ! i )
    throw std::invalid_argument(featureId);
  
  return i;
}


inline Component* IActivator::query(const std::string& featureId) const
{
  return onQuery(featureId);
}


template<typename I>
I* IActivator::query(const std::string& featureId) const
{
  Component* c = query(featureId);
  if(c)
    return c->queryInterface<I>();
  
  return 0;
}

} // namespace Cosmo

} // namespace Pt

#endif
