/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_ACTIVATE_INTERFACE_H
#define COSMO_ACTIVATE_INTERFACE_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IUnknown.h>

namespace Pt {

namespace Cosmo {

class IActivator;
class IComponentManager;

/** @brief Activation interface for required dependencies.

    Implement this interface to receive activation and deactivation
    callbacks. When all dependencies registered with
    %ComponentPlugin::registerDependency() are available, the component
    manager calls onActivate() with an %IActivator that provides access
    to the required interfaces.

    @ingroup Cosmo-Activation
*/
class IActivate : public IUnknown
{
  public:
    /** @brief Activates the component.

        @param activator Provides access to required dependency interfaces.
    */
    void activate(const IActivator& activator)
    {
      onActivate(activator);
    }

    /** @brief Deactivates the component.
    */
    void deactivate()
    {
      onDeactivate();
    }

  protected:
    /** @brief Called when all required dependencies are available.

        Resolve required interfaces here using activator.get<I>(featureId).

        @param activator Provides access to required dependency interfaces.
    */
    virtual void onActivate(const IActivator& activator) = 0;

    /** @brief Called when the component is deactivated.

        Clear cached dependency pointers here.
    */
    virtual void onDeactivate() = 0;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/IActivator.h>

#endif // include guard
