/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_AUTO_RELEASE_POOL_INTERFACE_H
#define COSMO_AUTO_RELEASE_POOL_INTERFACE_H

#include <Pt/Cosmo/Api.h>

namespace Pt {

namespace Cosmo {

class AutoReleasable;

/** @brief Auto-release pool interface.

    Manages a set of %AutoReleasable objects. When the pool is
    destroyed or reset, all attached releasables are released.

    @ingroup Cosmo-Memory
*/
class IAutoReleasePool
{
  friend class AutoReleasable;

  public:
    virtual ~IAutoReleasePool()
    { }

  protected:
    virtual void onAttachReleasable(AutoReleasable& r) = 0;

    virtual void onDetachReleasable(AutoReleasable& r) = 0;
};

/** @brief Auto-releasable resource.

    Base class for objects whose lifetime is managed by an
    %IAutoReleasePool. Attach to a pool in the constructor;
    detach automatically on destruction.

    @ingroup Cosmo-Memory
*/
class AutoReleasable
{
  friend class AutoReleasePool;

  public:
    AutoReleasable()
    : _pool(0)
    , _next(0)
    { }

    explicit AutoReleasable(IAutoReleasePool& pool)
    : _pool(&pool)
    , _next(0)
    { 
      _pool->onAttachReleasable(*this);
    }

    AutoReleasable(AutoReleasable&& other) noexcept
    : _pool(0)
    , _next(0)
    { 
      movePool(other);
    }

    virtual ~AutoReleasable()
    {
      detachPool();
    }

    AutoReleasable& operator=(AutoReleasable&& other) noexcept
    {
      if(this == &other)
        return *this;

      detachPool();
      movePool(other);
      return *this;
    }

    void reset()
    {
      detachPool();
      onRelease();
    }

  protected:
    virtual void onRelease() = 0;

  private:
    void detachPool()
    {
      if(_pool)
      {        
        _pool->onDetachReleasable(*this);
        _pool = 0;
      }
    }

    void movePool(AutoReleasable& other)
    {
      IAutoReleasePool* otherPool = other._pool;
      if(otherPool)
      {
        otherPool->onDetachReleasable(other);
        other._pool = 0;

        _pool = otherPool;
        _pool->onAttachReleasable(*this);
      }
    }

    AutoReleasable(const AutoReleasable& other) = delete;

    AutoReleasable& operator=(const AutoReleasable& other) = delete;

  private:
    IAutoReleasePool* _pool;
    AutoReleasable*   _next;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
