/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_TYPE_INTERFACE_H
#define COSMO_COMPONENT_TYPE_INTERFACE_H

#include <Pt/Cosmo/IUnknown.h>
#include <Pt/Cosmo/IEnumerable.h>

#include <typeinfo>

namespace Pt {

namespace Cosmo {

class Component;

/** @brief Component interface query.

    Provides runtime type information for a component, including
    feature ID lookup, interface presence checks, and interface
    retrieval via queryInterface().

    @ingroup Cosmo-Component
*/
class IComponentType
{
  public:
    /** @brief Destructor.
    */
	  virtual ~IComponentType()
	  {}

    /** @brief Returns true if the given feature ID is implemented.

        @param featureId The feature ID to check.
    */
    bool hasFeatureId(const char* featureId) const;

    /** @brief Returns the implemented feature IDs.
    */
    const IEnumerable<const char*>& featureIds() const;

    /** @brief Returns the class ID of the component.
    */
    const char* classId() const;

    /** @brief Returns true if the interface is implemented.
    */
    template <typename I>
    bool hasInterface() const;

    /** @brief Returns the interface or null if not implemented.

        @param c The component instance to query.
    */
    template <typename I>
    I* queryInterface(Component& c) const;

  protected:
    /** @brief Returns true if the given feature ID is implemented.
    */
    virtual bool onHasFeatureId(const char* featureId) const = 0;
    
    /** @brief Returns the implemented feature IDs.
    */
    virtual const IEnumerable<const char*>& onGetFeatureIds() const = 0;

    /** @brief Returns the class ID of the component.
    */
    virtual const char* onGetClassId() const = 0;

    /** @brief Returns true if the interface is implemented.
    */
    virtual bool onHasInterface(const std::type_info& ti) const = 0;

    /** @brief Returns the interface or null if the interface is not implemented.
    */
    virtual IUnknown* onQueryInterface(Component& c, 
                                       const std::type_info& ti) const = 0;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/Component.h>

namespace Pt {

namespace Cosmo {

inline bool IComponentType::hasFeatureId(const char* featureId) const
{
  return onHasFeatureId(featureId);
}


inline const IEnumerable<const char*>& IComponentType::featureIds() const
{
  return onGetFeatureIds();
}


inline const char* IComponentType::classId() const
{
  return onGetClassId();
}


template <typename I>
bool IComponentType::hasInterface() const
{
  const std::type_info& ti = typeid(I);
  return onHasInterface(ti);
}


template <typename I>
I* IComponentType::queryInterface(Component& c) const
{
  const std::type_info& ti = typeid(I);
  IUnknown* unknown = onQueryInterface(c, ti);
  return static_cast<I*>(unknown);
}

} // namespace Cosmo

} // namespace Pt

#endif // include guard
