/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_PLUGIN_INTERFACE_H
#define COSMO_COMPONENT_PLUGIN_INTERFACE_H

#include <Pt/Cosmo/ComponentMode.h>
#include <Pt/Cosmo/IComponentType.h>
#include <Pt/Cosmo/IEnumerable.h>

namespace Pt {

namespace Cosmo {

class Component;
class IComponentManager;

/** @brief Component plugin interface.

    A plugin describes a component class. It provides metadata such as
    class ID, feature IDs, dependencies, and component mode. The
    %IComponentManager uses plugins to create, initialize and destroy
    component instances.

    @ingroup Cosmo-Component
*/
class IComponentPlugin : public IComponentType
{
  friend class IComponentManager;

  public:
    /** @brief Destructor.
    */
	  virtual ~IComponentPlugin()
	  {}

    /** @brief Returns the feature IDs of the dependencies.
    */
    const IEnumerable<const char*>& dependencies() const;

    /** @brief Returns the component mode.
    */
    ComponentMode mode() const;

    /** @brief Returns the info string of the component.
    */
    const char* info() const;

    /** @brief Creates a component instance.
    */
    Component* create(const IComponentDeclaration* decl);

    /** @brief Destroys a component instance.
    */
    void destroy(Component* instance);

  protected:
    /** @brief The plugin is attached to a component manager.
    */
    virtual void onAttach(IComponentManager& cm, const std::string& instance) = 0;

    /** @brief The plugin is detached from a component manager.
    */
    virtual void onDetach(IComponentManager& cm, const std::string& instance) = 0;

    /** @brief The plugin is detached from a component manager.
    */
    virtual void onDetach(IComponentManager& cm) = 0;

    /** @brief Returns the feature IDs of the depencies.
    */
    virtual const IEnumerable<const char*>& onGetDependencies() const = 0;

    /** @brief Returns the component mode.
    */
    virtual ComponentMode onGetMode() const = 0;

    /** @brief Returns the info string of the component.
    */
    virtual const char* onGetInfo() const = 0;

    /** @brief Creates a component instance.
    */
    virtual Component* onCreate() = 0;

    /** @brief Destroys a component instance.
    */
    virtual void onDestroy(Component* instance) = 0;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/Component.h>

namespace Pt {

namespace Cosmo {

inline const IEnumerable<const char*>& IComponentPlugin::dependencies() const
{
  return onGetDependencies();
}


inline ComponentMode IComponentPlugin::mode() const
{
  return onGetMode();
}


inline const char* IComponentPlugin::info() const
{
  return onGetInfo();
}


inline Component* IComponentPlugin::create(const IComponentDeclaration* decl)
{
  Component* component = this->onCreate();
  component->init(this, decl);
  return component;
}


inline void IComponentPlugin::destroy(Component* instance)
{
  onDestroy(instance);
}

} // namespace Cosmo

} // namespace Pt

#endif
