/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_DECLARATION_INTERFACE_H
#define COSMO_COMPONENT_DECLARATION_INTERFACE_H

#include <Pt/Cosmo/Api.h>

namespace Pt {

namespace Cosmo {

/** @brief Component instance declaration.

    Represents a declared component instance as read from the
    application manifest. Provides the instance ID and the
    module requirement string.

    @ingroup Cosmo-Component
*/
class IComponentDeclaration
{
  public:
    /** @brief Destructor.
    */
	  virtual ~IComponentDeclaration()
	  {}

    /** @brief Returns the instance ID of the component.
    */
    const char* instanceId() const
    {
      return onGetInstanceId();
    }

    /** @brief Returns the module requirement string.
    */
    const char* require() const
    {
      return onGetRequire();
    }

  protected:
    virtual const char* onGetInstanceId() const = 0;

    virtual const char* onGetRequire() const = 0;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
