/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_COMPONENT_MANAGER_INTERFACE_H
#define COSMO_COMPONENT_MANAGER_INTERFACE_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IUnknown.h>
#include <Pt/Cosmo/ComponentInfo.h>
#include <Pt/Cosmo/IEnumerable.h>

#include <string>
#include <vector>
#include <stdexcept>

namespace Pt {

namespace Cosmo {

class IComponentPlugin;

/** @brief Component manager interface.

    Manages the lifecycle of component plugins and their instances.
    Plugins are registered, then loaded on demand or all at once.
    The component manager resolves dependencies and activates
    components in the correct order.

    @ingroup Cosmo-Component
*/
class IComponentManager : public IUnknown
{
  public:
    /** @brief Destructor.
    */
    virtual ~IComponentManager()
    {}

    /** @brief Registers component.
    */
    void registerComponent(IComponentPlugin& plugin,
                           const std::string& require,
                           const std::string& instance);

    /** @brief Loads all registered components.
    */
    void load();

    /** @brief Loads registered component.
    */
    void load(const std::string& instance);

    /** @brief Unloads a component plugin.
    */
    void unload(IComponentPlugin& plugin);

    /** @brief Unloads a component plugin by instance ID.
    */
    void unload(const std::string& instanceId);

    /** @brief Returns component infos
    */
    const IEnumerable<ComponentInfo>& components() const
    {
      return onGetComponents();
    }

  protected:
    /** @brief Registers component.
    */
    virtual void onRegisterComponent(IComponentPlugin& plugin,
                                     const std::string& require,
                                     const std::string& instance) = 0;


    /** @brief Loads all registered components.
    */
    virtual void onLoad() = 0;

    /** @brief Loads a component instance.
    */
    virtual void onLoadInstance(const std::string& instanceId) = 0;

    /** @brief Unloads a plugin and all components using it.
    */
    virtual void onUnload(IComponentPlugin& plugin) = 0;

    /** @brief Unloads a component instance.
    */
    virtual IComponentPlugin* onUnloadInstance(const std::string& instanceId) = 0;

    /** @brief Returns component infos.
    */
    virtual const IEnumerable<ComponentInfo>& onGetComponents() const = 0;
};

} // namespace Cosmo

} // namespace Pt

#include <Pt/Cosmo/IComponentPlugin.h>

namespace Pt {

namespace Cosmo {

inline void IComponentManager::registerComponent(IComponentPlugin& plugin,
                                                 const std::string& require,
                                                 const std::string& instance)
{
  plugin.onAttach(*this, instance);
  onRegisterComponent(plugin, require, instance);
}


inline void IComponentManager::load()
{
  onLoad();
}


inline void IComponentManager::load(const std::string& instance)
{
  onLoadInstance(instance);
}


inline void IComponentManager::unload(IComponentPlugin& plugin)
{
  onUnload(plugin);
  plugin.onDetach(*this);
}


inline void IComponentManager::unload(const std::string& instanceId)
{
  IComponentPlugin* plugin = onUnloadInstance(instanceId);
  if(plugin)
    plugin->onDetach(*this, instanceId);
}

} // namespace Cosmo

} // namespace Pt

#endif
