/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_CONNECT_INTERFACE_H
#define COSMO_CONNECT_INTERFACE_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IUnknown.h>

namespace Pt {

namespace Cosmo {

class Component;
class IComponentPlugin;

/** @brief Interface for optional component connections.

    Implement this interface to react to other components becoming
    available or unavailable at runtime without requiring them as
    activation dependencies. Filter candidates in onIsConnectable()
    using hasFeatureId() or hasInterface() checks.

    @ingroup Cosmo-Connect
*/
class IConnect : public IUnknown
{
  public:
    /** @brief Notifies that a connectable component was loaded.

        @param c The component that was added.
    */
    void addComponent(Component& c)
    {
      onComponentAdded(c);
    }

    /** @brief Notifies that a connectable component is being removed.

        @param c The component that is being removed.
    */
    void removeComponent(Component& c)
    {
      onComponentRemoved(c);
    }

    /** @brief Returns true if the plugin is connectable.

        @param p The plugin to check.
    */
    bool isConnectable(IComponentPlugin& p) const
    { 
      return onIsConnectable(p); 
    }

  protected:
    /** @brief Determines whether a plugin is connectable.

        Use hasFeatureId() or hasInterface() to filter candidates.

        @param p The plugin to check.
    */
    virtual bool onIsConnectable(IComponentPlugin& p) const = 0;

    /** @brief Called when a matching component is loaded.

        Use queryInterface() on the component to retrieve the
        optional interface.

        @param c The component that was added.
    */
    virtual void onComponentAdded(Component& c) = 0;

    /** @brief Called when a matching component is being removed.

        @param c The component that is being removed.
    */
    virtual void onComponentRemoved(Component& c) = 0;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
