/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_DEPENDENCY_INFO_INTERFACE_H
#define COSMO_DEPENDENCY_INFO_INTERFACE_H

#include <Pt/Cosmo/Api.h>

#include <string>

namespace Pt {

namespace Cosmo {

/** @brief Dependency information.

    Describes a single dependency of a component, including its
    feature ID, the resolved instance ID, and whether the dependency
    has been successfully resolved.

    @ingroup Cosmo-Activation
*/
class IDependencyInfo
{
  public:
    /** @brief Destructor.
    */
    virtual ~IDependencyInfo()
    {}

    /** @brief Returns the feature ID of the dependency.
    */
    const std::string& featureId() const
    {
      return onGetFeatureId();
    }

    /** @brief Returns the instance ID of the resolved component.
    */
    const std::string& instanceId() const
    {
      return onGetInstanceId();
    }

    /** @brief Returns true if the dependency is resolved.
    */
    bool isResolved() const
    {
      return onIsResolved();
    }

    void setTarget(const std::string& instanceId,
                   bool isResolved)
    {
      onSetTarget(instanceId, isResolved);
    }

  protected:
    virtual const std::string& onGetFeatureId() const = 0;

    virtual const std::string& onGetInstanceId() const = 0;

    virtual bool onIsResolved() const = 0;

    virtual void onSetTarget(const std::string& instanceId,
                             bool isResolved) = 0;
};

} // namespace Cosmo

} // namespace Pt

#endif
