/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_LAUNCHER_INTERFACE_H
#define COSMO_LAUNCHER_INTERFACE_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/IUnknown.h>

namespace Pt {

namespace Cosmo {

/** @brief Launcher strategy interface.

    Required by %Main::run(). The launcher role must be provided by a
    user-defined component. The launcher can either execute a single
    task or enter a loop to run an application depending on its
    purpose.

    @ingroup Cosmo-Startup
*/
class ILauncher : public IUnknown
{
  public:
    /** @brief Starts the launcher.
    */
    void launch()
    {
      onLaunch();
    }

    /** @brief Requests the launcher to exit.
    */
    void exit()
    {
      onExit();
    }

  protected:
    /** @brief Called to start the launcher.
    */
    virtual void onLaunch() = 0;

    /** @brief Called to exit the launcher.
    */
    virtual void onExit() = 0;
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
