/**
  Copyright (C) 2012 Marc Boris Duerner

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef COSMO_MAIN_COMPONENT_H
#define COSMO_MAIN_COMPONENT_H

#include <Pt/Cosmo/Api.h>
#include <Pt/Cosmo/Component.h>
#include <Pt/Cosmo/ComponentPlugin.h>

namespace Pt {

namespace Cosmo {

class MainImpl;
class MainPlugin;
class ComponentManager;

/** @brief Main component.

    Entry point for a Cosmo-based application. Ties together the
    %ComponentManager, plugin loading, and the application main loop
    driven by an %ILauncher component.

    @ingroup Cosmo-Startup
*/
class PT_COSMO_API Main : public Component
{
  public:
    template <typename I>
    I* getInterface();

  public:
    /** @brief Constructs the main component.

        @param argc Reference to the argument count.
        @param argv The argument array.
        @param cm The component manager to use.
    */
    Main(int& argc, char** argv, ComponentManager& cm);
    
    /** @brief Destructor.
    */
    virtual ~Main();

    /** @brief Launches the application.

        Loads all registered components and invokes the %ILauncher.
    */
    void run();

    MainImpl& impl();
  
  private:
    MainPlugin*  _mainPlugin;
    MainImpl*    _impl;
};

/** @internal @brief Main component factory.
*/
class MainFactory
{
  public:
    /** @brief Constructor.
    */
    explicit MainFactory(Main& main)
    : _main(&main)
    {}

    Component* create()
    { return _main; }

    void destroy(Component* instance)
    { }

  private:
    Main* _main;
};

/** @internal @brief Main component plugin.
*/
class MainPlugin : public ComponentPlugin<Main, MainFactory>
{
  public:
    static const char* FeatureId()
    { return "Cosmo.Main"; }

    static const char* ClassId()
    { return "Cosmo.Main"; }

    static const char* Info()
    { return "Cosmo.Default"; }

  public:
    MainPlugin(Main& m);
};

} // namespace Cosmo

} // namespace Pt

#endif // include guard
