// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// Copyright (c) 2007 Marc Boris Duerner
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef Pt_Timespan_h
#define Pt_Timespan_h

#include "Pt/Api.h"
#include "Pt/Timestamp.h"


namespace Pt {

/** @brief  Represents time spans up to microsecond resolution.
*/
class PT_API Timespan
{
    public:
        typedef Timestamp::TimeDiff TimeDiff;
        //! @brief Creates a zero Timespan.
        Timespan();

        //! @brief Creates a Timespan.
        Timespan(TimeDiff microseconds);

        /** @brief Creates a Timespan.
            Useful for creating a Timespan from a struct timeval.
        */
        Timespan(long seconds, long microseconds);

        //! @brief Creates a Timespan.
        Timespan(int days, int hours, int minutes, int seconds, int microseconds);

        //! @brief Creates a Timespan from another one.
        Timespan(const Timespan& timespan);

        //! @brief Destroys the Timespan.
        ~Timespan();

        //! @brief Assignment operator.
        Timespan& operator = (const Timespan& timespan);

        //! @brief Assignment operator.
        Timespan& operator = (TimeDiff microseconds);

        //! @brief Assigns a new span.
        Timespan& assign(int days, int hours, int minutes, int seconds, int microseconds);

        /** @brief Assigns a new span.
            Useful for assigning from a struct timeval.
        */
        Timespan& assign(long seconds, long microseconds);

        //! @brief Swaps the Timespan with another one.
        void swap(Timespan& timespan);


        bool operator == (const Timespan& ts) const;
        bool operator != (const Timespan& ts) const;
        bool operator >  (const Timespan& ts) const;
        bool operator >= (const Timespan& ts) const;
        bool operator <  (const Timespan& ts) const;
        bool operator <= (const Timespan& ts) const;

        bool operator == (TimeDiff microseconds) const;
        bool operator != (TimeDiff microseconds) const;
        bool operator >  (TimeDiff microseconds) const;
        bool operator >= (TimeDiff microseconds) const;
        bool operator <  (TimeDiff microseconds) const;
        bool operator <= (TimeDiff microseconds) const;

        Timespan operator + (const Timespan& d) const;
        Timespan operator - (const Timespan& d) const;
        Timespan& operator += (const Timespan& d);
        Timespan& operator -= (const Timespan& d);

        Timespan operator + (TimeDiff microseconds) const;
        Timespan operator - (TimeDiff microseconds) const;
        Timespan& operator += (TimeDiff microseconds);
        Timespan& operator -= (TimeDiff microseconds);

        //! @brief Returns the number of days.
        int days() const;

        //! @brief Returns the number of hours (0 to 23).
        int hours() const;

        //! @brief Returns the total number of hours.
        int totalHours() const;

        //! @brief Returns the number of minutes (0 to 59).
        int minutes() const;

        //! @brief Returns the total number of minutes.
        int totalMinutes() const;

        //! @brief Returns the number of seconds (0 to 59).
        int seconds() const;

        //! @brief Returns the total number of seconds.
        int totalSeconds() const;

        //! @brief Returns the number of milliseconds (0 to 999).
        int milliseconds() const;

        //! @brief Returns the total number of milliseconds.
        TimeDiff totalMilliseconds() const;

        /** @brief Returns the fractions of a millisecond in microseconds (0 to 999).
        */ 
        int microseconds() const;

        /** @brief Returns the fractions of a second in microseconds (0 to 999).
        */ 
        int useconds() const;
 
        //! @brief Returns the total number of microseconds.
        TimeDiff totalMicroseconds() const;

        //! @brief The number of microseconds in a millisecond.
        static const TimeDiff Milliseconds;

        //! @brief The number of microseconds in a second.
        static const TimeDiff Seconds;

        //! @brief The number of microseconds in a minute.
        static const TimeDiff Minutes;

        //! @brief The number of microseconds in a hour.
        static const TimeDiff Hours;

        //! @brief The number of microseconds in a day.
        static const TimeDiff Days;

    private:
        TimeDiff _span;
};


//
// inlines
//
inline int Timespan::days() const
{
	return int(_span/Days);
}


inline int Timespan::hours() const
{
	return int((_span/Hours) % 24);
}

	
inline int Timespan::totalHours() const
{
	return int(_span/Hours);
}

	
inline int Timespan::minutes() const
{
	return int((_span/Minutes) % 60);
}

	
inline int Timespan::totalMinutes() const
{
	return int(_span/Minutes);
}

	
inline int Timespan::seconds() const
{
	return int((_span/Seconds) % 60);
}

	
inline int Timespan::totalSeconds() const
{
	return int(_span/Seconds);
}

	
inline int Timespan::milliseconds() const
{
	return int((_span/Milliseconds) % 1000);
}

	
inline Timespan::TimeDiff Timespan::totalMilliseconds() const
{
	return _span/Milliseconds;
}

	
inline int Timespan::microseconds() const
{
	return int(_span % 1000);
}


inline int Timespan::useconds() const
{
	return int(_span % 1000000);
}

	
inline Timespan::TimeDiff Timespan::totalMicroseconds() const
{
	return _span;
}


inline bool Timespan::operator == (const Timespan& ts) const
{
	return _span == ts._span;
}


inline bool Timespan::operator != (const Timespan& ts) const
{
	return _span != ts._span;
}


inline bool Timespan::operator >  (const Timespan& ts) const
{
	return _span > ts._span;
}


inline bool Timespan::operator >= (const Timespan& ts) const
{
	return _span >= ts._span;
}


inline bool Timespan::operator <  (const Timespan& ts) const
{
	return _span < ts._span;
}


inline bool Timespan::operator <= (const Timespan& ts) const
{
	return _span <= ts._span;
}


inline bool Timespan::operator == (TimeDiff microseconds) const
{
	return _span == microseconds;
}


inline bool Timespan::operator != (TimeDiff microseconds) const
{
	return _span != microseconds;
}


inline bool Timespan::operator >  (TimeDiff microseconds) const
{
	return _span > microseconds;
}


inline bool Timespan::operator >= (TimeDiff microseconds) const
{
	return _span >= microseconds;
}


inline bool Timespan::operator <  (TimeDiff microseconds) const
{
	return _span < microseconds;
}


inline bool Timespan::operator <= (TimeDiff microseconds) const
{
	return _span <= microseconds;
}


inline void swap(Timespan& s1, Timespan& s2)
{
	s1.swap(s2);
}


} // namespace Poco


#endif // Foundation_Timespan_INCLUDED
