// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// Copyright (C) 2006-2007, Marc Boris Duerner
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef Pt_Timestamp_h
#define Pt_Timestamp_h

#include <Pt/Api.h>
#include <Pt/Types.h>
#include <ctime>


namespace Pt {

/** @brief Monotonic time value
    A Timestamp stores a monotonic time value with (theoretical)
    microseconds resolution. Timestamps can be compared with each other
    and simple arithmetics are supported.Timestamps are UTC
    (Coordinated Universal Time) based and thus independent of the timezone
    in effect on the system.
*/
class PT_API Timestamp
{
    public:
        //! @brief monotonic UTC time value in microsecond resolution
        typedef Pt::int64_t TimeVal;

        //! @brief monotonic UTC time value in 100 nanosecond resolution
        typedef Pt::int64_t UtcTimeVal;

        //! @brief difference between two timestamps in microseconds
        typedef Pt::int64_t TimeDiff;  

        //! @brief Creates a timestamp with the current time.
        Timestamp();

        /// @brief Creates a timestamp from the given time value.
        Timestamp(TimeVal tv);

        /// @brief Copy constructor.
        Timestamp(const Timestamp& other);

        /// @brief Destroys the timestamp
        ~Timestamp();

        Timestamp& operator = (const Timestamp& other);

        Timestamp& operator = (TimeVal tv);

        /// @brief Swaps the Timestamp with another one.
        void swap(Timestamp& timestamp);

        /// @brief Updates the Timestamp with the current time.
        void update();

        bool operator == (const Timestamp& ts) const;
        bool operator != (const Timestamp& ts) const;
        bool operator >  (const Timestamp& ts) const;
        bool operator >= (const Timestamp& ts) const;
        bool operator <  (const Timestamp& ts) const;
        bool operator <= (const Timestamp& ts) const;

        Timestamp  operator +  (TimeDiff d) const;
        Timestamp  operator -  (TimeDiff d) const;
        TimeDiff   operator -  (const Timestamp& ts) const;
        Timestamp& operator += (TimeDiff d);
        Timestamp& operator -= (TimeDiff d);

        /** @brief Returns the timestamp expressed in time_t.
            time_t base time is midnight, January 1, 1970. The resolution
            is one second.
        */
        time_t epochTime() const;

        /** @brief Returns the timestamp expressed in UTC-based time
            UTC base time is midnight, October 15, 1582. The resolution
            is 100 nanoseconds.
        */
        UtcTimeVal utcTime() const;

        /** @brief Returns the timestamp in microseconds
            Returns the timestamp expressed in microseconds since the Unix
            epoch, midnight, January 1, 1970.
        */
        TimeVal epochMicroseconds() const;

        /** @brief Returns the elapsed time
            Returns the time elapsed since the time denoted by
            the timestamp. Equivalent to Timestamp() - *this.
        */
        TimeDiff elapsed() const;

        /** @brief Check if time has elapsed
            Returns true if the given interval has passed
            since the time denoted by the timestamp.
        */
        bool isElapsed(TimeDiff interval) const;

        //! @brief Creates a timestamp from a time_t.
        static Timestamp fromEpochTime(time_t t);

        //! @brief Creates a timestamp from a UTC time value.
        static Timestamp fromUtcTime(UtcTimeVal val);

        /** @brief Returns the resolution in units per second.
            Since the timestamp has microsecond resolution,
            the returned value is always 1000000.
        */
        static TimeVal resolution();

    #if defined(_WIN32)
        static Timestamp fromFileTimeNP(UInt32 fileTimeLow, UInt32 fileTimeHigh);
        void toFileTimeNP(UInt32& fileTimeLow, UInt32& fileTimeHigh) const;
    #endif

    private:
        TimeVal _ts;
};


inline bool Timestamp::operator == (const Timestamp& ts) const
{
	return _ts == ts._ts;
}


inline bool Timestamp::operator != (const Timestamp& ts) const
{
	return _ts != ts._ts;
}


inline bool Timestamp::operator >  (const Timestamp& ts) const
{
	return _ts > ts._ts;
}


inline bool Timestamp::operator >= (const Timestamp& ts) const
{
	return _ts >= ts._ts;
}


inline bool Timestamp::operator <  (const Timestamp& ts) const
{
	return _ts < ts._ts;
}


inline bool Timestamp::operator <= (const Timestamp& ts) const
{
	return _ts <= ts._ts;
}


inline Timestamp Timestamp::operator + (Timestamp::TimeDiff d) const
{
	return Timestamp(_ts + d);
}


inline Timestamp Timestamp::operator - (Timestamp::TimeDiff d) const
{
	return Timestamp(_ts - d);
}


inline Timestamp::TimeDiff Timestamp::operator - (const Timestamp& ts) const
{
	return _ts - ts._ts;
}


inline Timestamp& Timestamp::operator += (Timestamp::TimeDiff d)
{
	_ts += d;
	return *this;
}


inline Timestamp& Timestamp::operator -= (Timestamp::TimeDiff d)
{
	_ts -= d;
	return *this;
}


inline time_t Timestamp::epochTime() const
{
	return time_t(_ts/resolution());
}


inline Timestamp::UtcTimeVal Timestamp::utcTime() const
{
	return _ts*10 + (TimeDiff(0x01b21dd2) << 32) + 0x13814000;
}


inline Timestamp::TimeVal Timestamp::epochMicroseconds() const
{
	return _ts;
}


inline Timestamp::TimeDiff Timestamp::elapsed() const
{
	Timestamp now;
	return now - *this;
}


inline bool Timestamp::isElapsed(Timestamp::TimeDiff interval) const
{
	Timestamp now;
	Timestamp::TimeDiff diff = now - *this;
	return diff >= interval;
}


inline Timestamp::TimeVal Timestamp::resolution()
{
	return 1000000;
}


inline void swap(Timestamp& s1, Timestamp& s2)
{
	s1.swap(s2);
}


} // namespace Pt

#endif
