nobase_include_HEADERS = \
	Pt/Allocator.h \
	Pt/Any.h \
	Pt/Api.h \
	Pt/Application.h \
	Pt/Arg.h \
	Pt/Atomicity.cw.x86.h \
	Pt/Atomicity.gcc.arm.h \
	Pt/Atomicity.gcc.avr32.h \
	Pt/Atomicity.gcc.mips.h \
	Pt/Atomicity.gcc.ppc.h \
	Pt/Atomicity.gcc.sparc.h \
	Pt/Atomicity.gcc.x86_64.h \
	Pt/Atomicity.gcc.x86.h \
	Pt/Atomicity.generic.h \
	Pt/Atomicity.h \
	Pt/Atomicity.pthread.h \
	Pt/Atomicity.sun.h \
	Pt/Atomicity.windows.h \
	Pt/Base64Codec.h \
	Pt/Byteorder.h \
	Pt/Callable.h \
	Pt/Callable.tpp \
	Pt/Char.h \
	Pt/Composer.h \
	Pt/Connectable.h \
	Pt/Connection.h \
	Pt/ConstMethod.h \
	Pt/ConstMethod.tpp \
	Pt/ConversionError.h \
	Pt/Convert.h \
	Pt/Date.h \
	Pt/DateTime.h \
	Pt/Decomposer.h \
	Pt/Delegate.h \
	Pt/Delegate.tpp \
	Pt/Deserializer.h \
	Pt/Event.h \
	Pt/Facets.h \
	Pt/FixupInfo.h \
	Pt/Formatter.h \
	Pt/Function.h \
	Pt/Function.tpp \
	Pt/Invokable.h \
	Pt/Invokable.tpp \
	Pt/Main.h \
	Pt/Method.h \
	Pt/Method.tpp \
	Pt/NonCopyable.h \
	Pt/Pack1.h \
	Pt/PackPop.h \
	Pt/PageAllocator.h \
	Pt/PoolAllocator.h \
	Pt/RefCounted.h \
	Pt/Regex.h \
	Pt/SerializationContext.h \
	Pt/SerializationError.h \
	Pt/SerializationInfo.h \
	Pt/SerializationSurrogate.h \
	Pt/Serializer.h \
	Pt/Settings.h \
	Pt/Signal.h \
	Pt/Signal.tpp \
	Pt/Singleton.h \
	Pt/Slot.h \
	Pt/Slot.tpp \
	Pt/SmartPtr.h \
	Pt/SourceInfo.h \
	Pt/StringData.h \
	Pt/StringData.tpp \
	Pt/String.h \
	Pt/StringStream.h \
	Pt/String.tpp \
	Pt/TextBuffer.h \
	Pt/TextCodec.h \
	Pt/TextStream.h \
	Pt/Time.h \
	Pt/Timespan.h \
	Pt/TypeInfo.h \
	Pt/Types.h \
	Pt/TypeTraits.h \
	Pt/Utf8Codec.h \
	Pt/Variant.h \
	Pt/Vector2d.h \
	Pt/Vector2d.tpp \
	Pt/Void.h \
	Pt/System/Api.h \
	Pt/System/Application.h \
	Pt/System/Clock.h \
	Pt/System/Condition.h \
	Pt/System/Directory.h \
	Pt/System/EventLoop.h \
	Pt/System/EventSink.h \
	Pt/System/EventSource.h \
	Pt/System/FileDevice.h \
	Pt/System/File.h \
	Pt/System/FileInfo.h \
	Pt/System/IODevice.h \
	Pt/System/IOError.h \
	Pt/System/IOStream.h \
	Pt/System/Library.h \
	Pt/System/Mutex.h \
	Pt/System/Pipe.h \
	Pt/System/Plugin.h \
	Pt/System/Process.h \
	Pt/System/Queue.h \
	Pt/System/Selectable.h \
	Pt/System/Selector.h \
	Pt/System/Semaphore.h \
	Pt/System/SerialDevice.h \
	Pt/System/StreamBuffer.h \
	Pt/System/SystemError.h \
	Pt/System/Thread.h \
	Pt/System/Timer.h \
	Pt/System/Url.h \
	Pt/Net/AddrInfo.h \
	Pt/Net/Api.h \
	Pt/Net/TcpServer.h \
	Pt/Net/TcpSocket.h \
	Pt/Net/UdpSocket.h

