nobase_include_HEADERS = \
	Pt/Allocator.h \
	Pt/Any.h \
	Pt/Api.h \
	Pt/Arg.h \
	Pt/Atomicity.h \
	Pt/Base64Codec.h \
	Pt/Byteorder.h \
	Pt/Callable.h \
	Pt/Callable.tpp \
	Pt/Char.h \
	Pt/Composer.h \
	Pt/Connectable.h \
	Pt/Connection.h \
	Pt/ConstMethod.h \
	Pt/ConstMethod.tpp \
	Pt/ConversionError.h \
	Pt/Convert.h \
	Pt/Date.h \
	Pt/DateTime.h \
	Pt/Decomposer.h \
	Pt/Delegate.h \
	Pt/Delegate.tpp \
	Pt/Deserializer.h \
	Pt/Event.h \
	Pt/Facets.h \
	Pt/FixupInfo.h \
	Pt/Formatter.h \
	Pt/Function.h \
	Pt/Function.tpp \
	Pt/Invokable.h \
	Pt/Invokable.tpp \
	Pt/LiteralPtr.h \
	Pt/Locale.h \
	Pt/Main.h \
	Pt/Method.h \
	Pt/Method.tpp \
	Pt/NonCopyable.h \
	Pt/Pack1.h \
	Pt/PackPop.h \
	Pt/PageAllocator.h \
	Pt/PoolAllocator.h \
	Pt/RefCounted.h \
	Pt/Regex.h \
	Pt/SerializationContext.h \
	Pt/SerializationError.h \
	Pt/SerializationInfo.h \
	Pt/SerializationSurrogate.h \
	Pt/Serializer.h \
	Pt/Settings.h \
	Pt/Signal.h \
	Pt/Signal.tpp \
	Pt/Singleton.h \
	Pt/Slot.h \
	Pt/Slot.tpp \
	Pt/SmartPtr.h \
	Pt/SourceInfo.h \
	Pt/StringData.h \
	Pt/StringData.tpp \
	Pt/String.h \
	Pt/StringStream.h \
	Pt/String.tpp \
	Pt/TextBuffer.h \
	Pt/TextCodec.h \
	Pt/TextStream.h \
	Pt/Time.h \
	Pt/Timespan.h \
	Pt/TypeInfo.h \
	Pt/Types.h \
	Pt/TypeTraits.h \
	Pt/Utf8Codec.h \
	Pt/Variant.h \
	Pt/Void.h \
	Pt/Cma/Api.h \
	Pt/Cma/ComponentBuilder.h \
	Pt/Cma/ComponentFactory.h \
	Pt/Cma/Component.h \
	Pt/Cma/ComponentLibrary.h \
	Pt/Cma/IAggregated.h \
	Pt/Cma/IComponentBuilder.h \
	Pt/Cma/IPrefs.h \
	Pt/Cma/ITestSuite.h \
	Pt/Cma/IUnknown.h \
	Pt/Cma/TypeId.h \
	Pt/System/Api.h \
	Pt/System/Application.h \
	Pt/System/Clock.h \
	Pt/System/Condition.h \
	Pt/System/Directory.h \
	Pt/System/EventLoop.h \
	Pt/System/EventSink.h \
	Pt/System/EventSource.h \
	Pt/System/FileDevice.h \
	Pt/System/File.h \
	Pt/System/FileInfo.h \
	Pt/System/IODevice.h \
	Pt/System/IOError.h \
	Pt/System/IOStream.h \
	Pt/System/Library.h \
	Pt/System/MainLoop.h \
	Pt/System/Mutex.h \
	Pt/System/Pipe.h \
	Pt/System/Plugin.h \
	Pt/System/Process.h \
	Pt/System/Queue.h \
	Pt/System/Selectable.h \
	Pt/System/Semaphore.h \
	Pt/System/SerialDevice.h \
	Pt/System/StreamBuffer.h \
	Pt/System/SystemError.h \
	Pt/System/Thread.h \
	Pt/System/Timer.h \
	Pt/System/Url.h \
	Pt/System/LogLevel.h \
	Pt/System/LogChannel.h \
	Pt/System/Logger.h \
	Pt/Net/AddrInfo.h \
	Pt/Net/Api.h \
	Pt/Net/TcpServer.h \
	Pt/Net/TcpSocket.h \
	Pt/Net/UdpSocket.h \
	Pt/Unit/Api.h \
	Pt/Unit/Application.h \
	Pt/Unit/Assertion.h \
	Pt/Unit/RegisterTest.h \
	Pt/Unit/Reporter.h \
	Pt/Unit/TestCase.h \
	Pt/Unit/TestContext.h \
	Pt/Unit/TestFixture.h \
	Pt/Unit/Test.h \
	Pt/Unit/TestMain.h \
	Pt/Unit/TestMethod.h \
	Pt/Unit/TestProtocol.h \
	Pt/Unit/TestSuite.h \
	Pt/Unit/TextProtocol.h \
	Pt/Http/Api.h \
	Pt/Http/Client.h \
	Pt/Http/Message.h \
	Pt/Http/MessageHeader.h \
	Pt/Http/Reply.h \
	Pt/Http/ReplyHeader.h \
	Pt/Http/Request.h \
	Pt/Http/RequestHeader.h \
	Pt/Http/Responder.h \
	Pt/Http/Server.h \
	Pt/Http/Service.h \
	Pt/Reflex/Api.h \
	Pt/Reflex/MethodInfo.h \
	Pt/Reflex/PropertyInfo.h \
	Pt/Reflex/Reflectable.h \
	Pt/Reflex/Type.h \
	Pt/Xml/Api.h \
	Pt/Xml/Characters.h \
	Pt/Xml/Comment.h \
	Pt/Xml/DocTypeDeclaration.h \
	Pt/Xml/EndDocument.h \
	Pt/Xml/EndElement.h \
	Pt/Xml/EntityResolver.h \
	Pt/Xml/NamespaceContext.h \
	Pt/Xml/Namespace.h \
	Pt/Xml/Node.h \
	Pt/Xml/ProcessingInstruction.h \
	Pt/Xml/QName.h \
	Pt/Xml/StartElement.h \
	Pt/Xml/XmlDeclaration.h \
	Pt/Xml/XmlDeserializer.h \
	Pt/Xml/XmlError.h \
	Pt/Xml/XmlFormatter.h \
	Pt/Xml/XmlReader.h \
	Pt/Xml/XmlSerializationContext.h \
	Pt/Xml/XmlSerializer.h \
	Pt/Xml/XmlWriter.h \
	Pt/XmlRpc/Api.h \
	Pt/XmlRpc/Client.h \
	Pt/XmlRpc/Fault.h \
	Pt/XmlRpc/Formatter.h \
	Pt/XmlRpc/HttpClient.h \
	Pt/XmlRpc/RemoteProcedure.h \
	Pt/XmlRpc/Responder.h \
	Pt/XmlRpc/Result.h \
	Pt/XmlRpc/Scanner.h \
	Pt/XmlRpc/Service.h
