nobase_include_HEADERS = \
	Allocator.h \
	Any.h \
	Api.h \
	Application.h \
	Arg.h \
	Atomicity.cw.x86.h \
	Atomicity.gcc.arm.h \
	Atomicity.gcc.avr32.h \
	Atomicity.gcc.mips.h \
	Atomicity.gcc.ppc.h \
	Atomicity.gcc.sparc.h \
	Atomicity.gcc.x86_64.h \
	Atomicity.gcc.x86.h \
	Atomicity.generic.h \
	Atomicity.h \
	Atomicity.pthread.h \
	Atomicity.sun.h \
	Atomicity.windows.h \
	Base64Codec.h \
	Byteorder.h \
	Callable.h \
	Callable.tpp \
	Char.h \
	Composer.h \
	Connectable.h \
	Connection.h \
	ConstMethod.h \
	ConstMethod.tpp \
	ConversionError.h \
	Convert.h \
	Date.h \
	DateTime.h \
	Decomposer.h \
	Delegate.h \
	Delegate.tpp \
	Deserializer.h \
	Event.h \
	Facets.h \
	FixupInfo.h \
	Formatter.h \
	Function.h \
	Function.tpp \
	Invokable.h \
	Invokable.tpp \
	Main.h \
	Method.h \
	Method.tpp \
	NonCopyable.h \
	Pack1.h \
	PackPop.h \
	PageAllocator.h \
	PoolAllocator.h \
	RefCounted.h \
	Regex.h \
	SerializationContext.h \
	SerializationError.h \
	SerializationInfo.h \
	SerializationSurrogate.h \
	Serializer.h \
	Settings.h \
	Signal.h \
	Signal.tpp \
	Singleton.h \
	Slot.h \
	Slot.tpp \
	SmartPtr.h \
	SourceInfo.h \
	StringData.h \
	StringData.tpp \
	String.h \
	StringStream.h \
	String.tpp \
	TextBuffer.h \
	TextCodec.h \
	TextStream.h \
	Time.h \
	Timespan.h \
	TypeInfo.h \
	Types.h \
	TypeTraits.h \
	Utf8Codec.h \
	Variant.h \
	Vector2d.h \
	Vector2d.tpp \
	Void.h

nobase_nodist_include_HEADERS = \
        Pt/config.h
