#!/usr/bin/perl
########################################################################
# This is a really, really ugly code generator. It creates
# signal/slots-related implementations for Marc Duerner's
# signals/slots library (the STL version, not the pt-framework
# version).
#
# The generator was written by Stephan Beal. The underlying C++ code was
# written by Marc Duerner (he also acted as technical consultant and
# debuggerer for this generator).
#
########################################################################
# Configurable parts:
#
# - Change $NS to a single-token namespace name. Generated code will be
# in that namespace.
#
# - Change $HEADER_DIR to the directory part of your #include <INCLUDES/foo.hpp>
# calls for this code. By default it is equal to the namespace ($NS), e.g.
# it assumes that #include <$NS/foo.hpp> is valid.
#
# - Change $max_types to some number greater than 1. Passing that
# number to this app causes it to generate the unspecialized variants
# of the template declarations. Passing any smaller number generates
# specializations and overloads for lesser argument counts.
#
########################################################################
# Running it:
#
#  $0 NUMBER [-main [MAX]]
#
# Run with only one number, it generates template specializations for
# that many template arguments. It assumed that ${max_types}
# (default=8) is the "master" (unspecialized) template instantiation
# and generates slightly different class declarations when NUMBER is
# equal to the ${max_types} configuration value. If passed (NUMBER
# -main), it is equivalent to passing (NUMBER -main NUMBER), which
# means that the script should treat the second number (passed after
# -main) as the maximum number of template args (and therefor the
# unspecialized templates).
#
# The intension is that one run this script in a loop, similar to:
#
# for i in 5 4 3 2 1 0; ./generator $i -main 5; done > output.hpp
#
# The (-main 5) is used by lesser-arity templates so that we know how
# many placeholder types we need to use in certain template
# declarations. It is used by the "number 5" output to generate
# different declartions for the generated classes (e.g. main declation
# vs specialized, which are syntactically different).
#
# The output could then be #included into another project-specific
# header if needed (e.g. to wrap it into a namespace).
#
# The output contains several BEGIN_xxx and END_xxx markers. These are
# used only by the originating source tree's build process to separate
# various groups of classes for importation into their own files.
#
########################################################################
# Changing the namespace of the software:
#
# Change the $NS variable in this script and do a global search/replace
# on 'ptsigslot' in the non-generated files of the ptsigslot package:
#
#   perl -i -pe 's|ptsigslot|NewNamespace|g' *.cpp include/ptsigslot/*.hpp
#
#   mv include/ptsigslot include/NewNamespace
#
########################################################################
$NS = "ptsigslot";
$max_types = 8;
$HEADER_DIR = $NS;

$USAGE = "Usage: $0 NUMBER [-main [MAX]]\nwhere NUMBER is >= 0.\n";

$argc = $ARGV[0];
shift @ARGV;
if( @ARGV ) {
	foreach $a (@ARGV) {
		if( $a =~ /-+main/ ) {
			shift @ARGV;
			$v = $ARGV[0];
			$max_types = ($v ? $v : $argc);
		}
	}
}
if( ($argc < 0) || ($argc> $max_types ) ) {
        die $USAGE;
}

$main_inst = ($max_types==$argc);

$include_guard = "${NS}_${argc}_HPP_INCLUDED";
print "#ifndef ${include_guard}\n";
print "#define ${include_guard} 1\n";
print "// auto-generated [".localtime()."] by $0\n";

if( $main_inst ) {
print << 'EOF'
/***************************************************************************
 *   Copyright (C) 2004-2008 by Dr. Marc Boris Duerner                     *
 *   Copyright (C) 2005,2007-2008 Stephan Beal                             *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Library General Public License as       *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
EOF
;
}


@decl_typenames = ();
@argn = ();
# $arg_type_list_named: A1 a1, A2 a2, ... AN aN
$arg_type_list_named = "";
$i = 0;
for( $i = 1; $i <= $argc; $i++ ) {
	$comma = (($argc!=$i) ?', ':'');
        local $a = "A".$i;
        local $aname = "a${i}";
        push( @decl_typenames, $a );
        push( @argn, $aname );
        $arg_type_list_named .= "$a $aname".$comma;
}


########################################################################
# $arg_params_names: a1, a2, ... aN
$arg_params_names = join( ",", @argn );
print "//arg_params_names=$arg_params_names\n";

########################################################################
# $arg_tmpl_decl: class A1, class A2, ... class AN
$arg_tmpl_decl = (@decl_typenames
		  ? ("class ".join(", class ",@decl_typenames))
		  : '');
print "//arg_tmpl_decl=$arg_tmpl_decl\n";

########################################################################
# $comma_arg_tmpl_decl: $arg_tmpl_decl with leading comma
$comma_arg_tmpl_decl = (@decl_typenames
			 ? ','.${arg_tmpl_decl}
			 : '');
print "//comma_arg_tmpl_decl=$comma_arg_tmpl_decl\n";

########################################################################
# $arg_tmpl_types: A1, A2, ... AN
$arg_tmpl_types = join(',',@decl_typenames);
print "//arg_tmpl_types=$arg_tmpl_types\n";

########################################################################
# $comma_arg_tmpl_types: $arg_tmpl_types with leading comma
$comma_arg_tmpl_types = (@decl_typenames
			 ? ','.${arg_tmpl_types}
			 : '');
print "//comma_arg_tmpl_types=$comma_arg_tmpl_types\n";

########################################################################
# $arg_tmpl_decl_main_inst: class A1 = Void, ... class AN = Void
$arg_tmpl_decl_main_inst = '';
for( $i = 1; $i <= $max_types; ++$i ) {
  $comma = (($argc!=$i) ?', ':'');
  $arg_tmpl_decl_main_inst .= 'class A'.$i.' = Void'.$comma;
}
print "//arg_tmpl_decl_main_inst=$arg_tmpl_decl_main_inst\n";

@typelist = @decl_typenames;
for( $i=$argc; $i < $max_types; ++$i ) {
	push(@typelist,'Void');
}

########################################################################
# $arg_tmpl_decl_1toN: typename A1, ... typename AN
$arg_tmpl_decl_1toN = '';

########################################################################
# $arg_tmpl_spec_1toN: A1, ... AN
$arg_tmpl_spec_1toN = '';
if( $argc ) {
	for( $i = 1; $i <= $argc; ++$i ) {
		$comma = (($argc!=$i) ?', ':'');
		$arg_tmpl_decl_1toN .= 'typename A'.$i.$comma;
		$arg_tmpl_spec_1toN .= 'A'.$i.$comma;
	}
}
print "//arg_tmpl_decl_1toN=$arg_tmpl_decl_1toN\n";
print "//arg_tmpl_spec_1toN=$arg_tmpl_spec_1toN\n";

########################################################################
# $arg_tmpl_types_all: A1, A2, AN, ... Void, Void, Void
$arg_tmpl_types_all = join(',',@typelist);
print "//arg_tmpl_types_all=$arg_tmpl_types_all\n";

########################################################################
# $comma_arg_tmpl_types_all: $arg_tmpl_types_all with leading comma
$comma_arg_tmpl_types_all = ', '.$arg_tmpl_types_all;
print "//comma_arg_tmpl_types_all=$comma_arg_tmpl_types_all\n";

undef @decl_typenames;
undef @argn;


print "namespace $NS {\n";

########################################################################
# Invokable
print "// BEGIN_Invokable ${argc}\n";

if( $main_inst ) {
print << "EOF"
/**
Invokable is a type which can be "called" via
the invoke() member. It serves as a base type
for other types in the Pt signals/slots framework.
*/
template <${arg_tmpl_decl_main_inst}>
class Invokable {
EOF
;
} else {
print << "EOF"
// specialization
template <${arg_tmpl_decl}>
class Invokable<${arg_tmpl_types_all}> {
EOF
;
}

print << "EOF" # Invokable
    public:
        /** Does nothing. Does not throw. */
        virtual ~Invokable()
        {}

        /** Behaviour is determined by subclass implementations. */
        virtual void invoke(${arg_type_list_named}) const = 0;
};
// END_Invokable ${argc}
EOF
;

########################################################################
# BasicSlot<> 
if( $main_inst ) {
	print "// BEGIN_BasicSlot ${argc}\n";

    print << "EOF"
    /**
        BasicSlot is a base type for various "slot" types.
    */
EOF
;
    print "template < typename R,";
    for( $i = 1; $i <= $argc; ++$i ) {
	    $comma = (($i==$argc) ? '' : ', ');
	    print " typename A".$i." = Void".$comma;
    }
    print ">\n";
print << "EOF"
    class BasicSlot : public Slot {
        public:
            /**
            Creates a copy of this object and returns it. The caller
            owns the returned object.
            */
            virtual Slot* clone() const = 0;
    };
// END_BasicSlot ${argc}
EOF
;
} # $main_inst


########################################################################
# Callable
print "// BEGIN_Callable ${argc}\n";

if( $main_inst ) {
print << "EOF"
    /**
      Callable represents a "callable" type, which is fundamentally
      similar to an Invokable but is semantically richer.
    */
    template <typename R, ${arg_tmpl_decl_main_inst}>
    class Callable : public Invokable<${arg_tmpl_types}> {
EOF
;
} else {
print << "EOF"
    // specialization
    template <typename R${comma_arg_tmpl_decl}>
    class Callable<R${comma_arg_tmpl_types_all}> : public Invokable<${arg_tmpl_types}> {
EOF

}

print "\t\tpublic:\n";
#$i = 0;
#foreach $t (@typelist) {
#	++$i;
#	print "\t\ttypedef ".$t." Arg".$i."T;\n";
#}
print << "EOF" # Callable:
            typedef R ReturnT;
            enum { NumArgs = ${argc} };

        public:
            /**
              Creates a copy of this object and returns it. Caller owns
              the returned object.
            */
            virtual Callable* clone() const = 0;

            /** Exact behaviour is defined by subclass implementations. */
            virtual ReturnT operator()(${arg_type_list_named}) const = 0;

            /** Same as calling this->operator()(...). */
            ReturnT call(${arg_type_list_named}) const
            { return this->operator()(${arg_params_names}); }

            /** Same as calling this->operator()(...), except that the return value
            of that method is ignored. */
            void invoke(${arg_type_list_named}) const
            { this->operator()(${arg_params_names}); }
    };

EOF
;
print "// END_Callable ${argc}\n";


########################################################################
# signal
print "// BEGIN_Signal ${argc}\n";
if( $main_inst ) {
print << "EOF"
    /** Multicast Signal

        A Signal can be connected to multiple targets. The return
        value of the target(s) is/are ignored.
    */
    template <${arg_tmpl_decl_main_inst}>
    class Signal : public SignalBase {
EOF
;
} else {
print << "EOF"
    // specialization
    template <${arg_tmpl_decl}>
    class Signal<${arg_tmpl_types_all}> : public SignalBase {
EOF
;
}


print << "EOF" # Signal<>:
        public:
            typedef Invokable<${arg_tmpl_types_all}> InvokableT;

        public:
            /** Does nothing. */
            Signal()
            { }

            /** Deeply copies rhs. */
            Signal(const Signal& rhs)
            {
                Signal::operator=(rhs);
            }

            /**
            Connects slot to this signal, such that firing this signal
            will invoke slot.
            */
            template <typename R>
            Connection connect(const BasicSlot<R, ${arg_tmpl_types_all}>& slot)
            {
                return Connection(*this, slot.clone() );
            }

            /** The converse of connect(). */
            template <typename R>
            void disconnect(const BasicSlot<R, ${arg_tmpl_types_all}>& slot)
            {
                this->disconnectSlot(slot);
            }

            /**
            Invokes all slots connected to this signal, in an undefined
            order. Their return values are ignored. Calling of connected slots will
            be interrupted if a slot deletes this Signal object or throws an exception.
            */
            inline void send(${arg_type_list_named}) const
            {
                // The sentry will set the Signal to the sending state and
                // reset it to not-sending upon destruction. In the sending
                // state, removing connection will leave invalid connections
                // in the connection list to keep the iterator valid, but mark
                // the Signal dirty. If the Signal is dirty, all invalid
                // connections will be removed by the Sentry when it destructs..
                SignalBase::Sentry sentry(this);

                std::list<Connection>::const_iterator it = Connectable::connections().begin();
                std::list<Connection>::const_iterator end = Connectable::connections().end();

                for(; it != end; ++it)
                {
                    if( false == it->valid() || &( it->sender() ) != this  )
                        continue;

                    // The following scenarios must be considered when the
                    // slot is called:
                    // - The slot might get deleted and thus disconnected from
                    //   this signal
                    // - The slot might delete this signal and we must end
                    //   calling any slots immediately
                    // - A new Connection might get added to this Signal in
                    //   the slot
                    const InvokableT* invokable = static_cast<const InvokableT*>( it->slot().callable() );
                    invokable->invoke(${arg_params_names});

                    // if this signal gets deleted by the slot, the Sentry
                    // will be detached. In this case we bail out immediately
                    if( !sentry )
                        return;
                }
            }

            /** Same as send(...). */
            inline void operator()(${arg_type_list_named}) const
            { this->send(${arg_params_names}); }
    };

EOF
;
print "// END_Signal ${argc}\n";

print "// BEGIN_SignalSlot ${argc}\n";

if( $main_inst ) {
print << "EOF" # SignalSlot<>:
    /**
      SignalSlot is a "slot wrapper" for Signal objects. That is, it
      effectively converts a Signal object into a Slot object, so that it
      can be used as the target of another Signal. This allows chaining of
      Signals.
    */
    template <${arg_tmpl_decl_main_inst}>
    class SignalSlot : public BasicSlot<void${comma_arg_tmpl_types}>
    {
        public:
            /** Wraps signal. */
            SignalSlot(Signal<${arg_tmpl_types}>& signal)
            : _method( signal, &Signal<${arg_tmpl_types}>::send )
            {}

            /** Creates a clone of this object and returns it. Caller owns
            the returned object. */
            BasicSlot<void${comma_arg_tmpl_types}>* clone() const
            { return new SignalSlot(*this); }

            /** Returns a pointer to this object's internal Callable object. */
            virtual const void* callable() const
            {
                return &_method;
            }

            /** ??? */
            virtual bool opened(const Connection& c)
            {
                Connectable& connectable = _method.object();
                return connectable.opened(c);
            }

            /** ??? */
            virtual void closed(const Connection& c)
            {
                Connectable& connectable = _method.object();
                connectable.closed(c);
            }
            /** returns true if this object and rhs are equivalent. */
            virtual bool equals(const Slot& rhs) const
            {
                const SignalSlot* ss = dynamic_cast<const SignalSlot*>(&rhs);
                return ss ? (_method == ss->_method) : false;
            }

        private:
            mutable ConstMethod<void, Signal<${arg_tmpl_types}>${comma_arg_tmpl_types} > _method;
    };

    /** Creates a SignalSlot object from an equivalent Signal. */
    template <${arg_tmpl_decl}>
    SignalSlot<${arg_tmpl_types}> slot( Signal<${arg_tmpl_types}> & signal )
    { return SignalSlot<${arg_tmpl_types}>( signal ); }


    /** Connects the given signal and slot objects and returns that Connection
    object (which can normally be ignored). */
    template <typename R${comma_arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& signal, const BasicSlot<R${comma_arg_tmpl_types}>& slot)
    {
        return Connection(signal, slot.clone() );
    }



EOF
;
}

print << "EOF"

    //! Connects a Signal to a function.
    template <typename R${comma_arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& signal, R(*func)(${arg_tmpl_types}))
    {
        return connect( signal, slot(func) );
    }

    //! Connects a Signal to a member function.
    template <typename R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& signal, BaseT& object, R(ClassT::*memFunc)(${arg_tmpl_types}))
    {
        return connect( signal, slot(object, memFunc) );
    }

    //! Connects a Signal to a const member function.
    template <typename R, class ClassT${comma_arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& signal, ClassT& object, R(ClassT::*memFunc)(${arg_tmpl_types}) const)
    {
        return connect( signal, slot(object, memFunc) );
    }

    /// Connects a Signal to another Signal
/**
    template <${arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& sender, Signal<${arg_tmpl_types}>& receiver)
    {
        return connect( sender, slot(receiver) );
    }
*/

    template <typename R${comma_arg_tmpl_decl}>
    void disconnect(Signal<${arg_tmpl_types}>& signal, const BasicSlot<R${comma_arg_tmpl_types}>& slot)
    {
        return signal.disconnect( slot );
    }

    template <typename R${comma_arg_tmpl_decl}>
    void disconnect(Signal<${arg_tmpl_types}>& signal, R(*func)(${arg_tmpl_types}))
    {
        signal.disconnect( slot(func) );
    }

    template <typename R, typename BaseT, typename ClassT${comma_arg_tmpl_decl}>
    void disconnect(Signal<${arg_tmpl_types}>& signal, BaseT & object, R(ClassT::*memFunc)(${arg_tmpl_types}))
    {
        signal.disconnect( slot( object, memFunc ) );
    }

    template <typename R, typename ClassT${comma_arg_tmpl_decl}>
    void disconnect(Signal<${arg_tmpl_types}>& signal, ClassT & object, R(ClassT::*memFunc)(${arg_tmpl_types}) const)
    {
        signal.disconnect( slot( object, memFunc ) );
    }

    template <typename R${comma_arg_tmpl_decl}>
    void disconnect( Signal<${arg_tmpl_types}>& sender, Signal<${arg_tmpl_types}>& receiver )
    {
        sender.disconnect( slot(receiver) );
    }

EOF
;

if( 0 == $argc ) {
# connect(Signal<>,Signal<>) requires a special case non-template inline function
# to avoid multiple definition errors. Not quite sure why.
print << "EOF"
    /** Connects a Signal to another Signal. */
    inline Connection connect(Signal<>& sender, Signal<>& receiver)
    {
        return connect( sender, slot(receiver) );
    }
EOF
;
} else {
print << "EOF"
    /** Connects a Signal to another Signal. */
    template <${arg_tmpl_decl}>
    Connection connect(Signal<${arg_tmpl_types}>& sender, Signal<${arg_tmpl_types}>& receiver)
    {
        return connect( sender, slot(receiver) );
    }
EOF

}

print "// END_SignalSlot ${argc}\n";
print "// BEGIN_Function ${argc}\n";

if( $main_inst ) {
print << "EOF"
/**
 The Function class wraps free functions in the form of a Callable, for use
with the signals/slots framework.
*/
template < typename R,${arg_tmpl_decl_main_inst}>
class Function : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
} else {
print << "EOF"
template < typename R${comma_arg_tmpl_decl}>
class Function<R${comma_arg_tmpl_types_all}> : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
}

print << "EOF"
{
    public:
        /** The function signature wrapped by this class. */
        typedef R (*FuncT)(${arg_tmpl_types});

        /** Wraps func. */
        Function(FuncT func)
        : _funcPtr(func) { }

        /** Deeply copies f. */
        Function(const Function& f)
        { this->operator=(f); }

        /** Call the wrapped function, passing it the arguments as-is and returning
        its return value. */
        R operator()(${arg_type_list_named}) const
        { return (*_funcPtr)(${arg_params_names}); }

        /** Creates a clone of this object and returns it. The caller owns the returned object. */
        Function<R${comma_arg_tmpl_types}>* clone() const
        { return new Function(*this); }


#if 0
        /** Deeply copies function and returns this object. */
        Function& operator=(const Function& function)
        {
            if( this != &function ) {
                _funcPtr = function._funcPtr;
            }
            return (*this);
        }
#endif

        /** Returns true if rhs and this object point to the same function. */
        bool operator==(const Function& rhs) const
        {
            return (_funcPtr == rhs._funcPtr);
        }

    private:
        FuncT _funcPtr;
};
EOF
;

if( $main_inst ) {
print << "EOF"
/** FunctionSlot wraps Function objects so that they can act as
Slots.
*/
template < typename R,${arg_tmpl_decl_main_inst}>
class FunctionSlot : public BasicSlot<R${comma_arg_tmpl_types_all}>
{
    public:
        FunctionSlot(const Function<R${comma_arg_tmpl_types}>& func)
        : _func( func )
        {}

        /** Returns a pointer to this object's internal Callable. */
        virtual const void* callable() const
        { return &_func; }

        /** Creates a copy of this object and returns it. Caller owns the returned object. */
        Slot* clone() const
        { return new FunctionSlot(*this); }

        virtual bool opened(const Connection& c)
        { return true; }

        virtual void closed(const Connection& c)
        { }
        virtual bool equals(const Slot& slot) const
        {
            const FunctionSlot* fs = dynamic_cast<const FunctionSlot*>(&slot);
            return fs ? (_func == fs->_func) : false;
        }

    private:
        Function<R${comma_arg_tmpl_types}> _func;
}; // FunctionSlot

EOF
;
}


print << "EOF"

/** Creates and returns a Function wrapper for the given free/static function. */
template <typename R${comma_arg_tmpl_decl}>
Function<R${comma_arg_tmpl_types}> callable(R (*func)(${arg_type_list_named}))
{ return Function<R${comma_arg_tmpl_types}>(func); }

/** Creates and returns a FunctionSlot object for the given free/static function. */
template <typename R${comma_arg_tmpl_decl}>
FunctionSlot<R${comma_arg_tmpl_types}> slot( R (*func)(${arg_type_list_named}) )
{ return FunctionSlot<R${comma_arg_tmpl_types}>( callable(func) ); }

// END_Function ${argc}
EOF
;



print "// BEGIN_ConstMethod ${argc}\n";

if( $main_inst ) {
print << "EOF"
/**
    The ConstMethod class wraps const member functions as Callable objects
    so that they can be used with the signals/slots framework.
*/
template < typename R,typename ClassT,${arg_tmpl_decl_main_inst}>
class ConstMethod : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
} else {
print << "EOF"
template < typename R, typename ClassT${comma_arg_tmpl_decl}>
class ConstMethod<R,ClassT${comma_arg_tmpl_types_all}> : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
}

print << "EOF"
{
    public:
        /** Convenience typedef for the wrapped member function type. */
        typedef R (ClassT::*MemFuncT)(${arg_tmpl_types}) const;

        /** Wraps the given member function of the given object. */
        ConstMethod(ClassT& object, MemFuncT ptr)
        : _object(&object), _method(ptr)
        { }

        /** Deeply copies rhs. */
        ConstMethod(const ConstMethod& rhs)
        : Callable<R${comma_arg_tmpl_types_all}>()
        { this->operator=(rhs); }

        /** Returns a reference to this object's bound ClassT object. */
        ClassT& object()
        { return *_object;}

        /** Returns a const reference to this object's bound ClassT object. */
        const ClassT& object() const
        { return *_object;}

        /** Calls the bound member function of the bound object, passing all
        parameters to that member function. Returns the value of that member.
        */
        R operator()(${arg_type_list_named}) const
        { return (_object->*_method)(${arg_params_names}); }

        /** Creates a copy of this object and returns it.  Caller owns the returned object. */ 
        ConstMethod<R, ClassT${comma_arg_tmpl_types}>* clone() const
        { return new ConstMethod(*this); }

        /** Returns true if rhs and this object point to the same object and method. */
        bool operator==(const ConstMethod& rhs) const
        {
            return (_object == rhs._object) &&
                   (_method == rhs._method);
        }

    private:
        ClassT* _object;
        MemFuncT _method;
};

/** Creates and  returns a ConstMethod object from the given object and method pair. */
template <class R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
ConstMethod<R,ClassT${comma_arg_tmpl_types}> callable( ClassT & obj, R (BaseT::*ptr)(${arg_type_list_named}) const )
{ return ConstMethod<R,ClassT${comma_arg_tmpl_types}>(obj,ptr); }

EOF
;

if( $main_inst ) {
print << "EOF"
/**
ConstMethodSlot is a wrapper which allows ConstMethod objects to behave
like Slot objects.
*/
template < typename R, typename ClassT,${arg_tmpl_decl_main_inst}>
class ConstMethodSlot : public BasicSlot<R${comma_arg_tmpl_types_all}>
{
    public:
        /** Wraps the given ConstMethod object. */
        ConstMethodSlot(const ConstMethod<R, ClassT${comma_arg_tmpl_types}>& method)
        : _method( method )
        {}

        /** Creates a copy of this object and returns it. Caller owns the returned object. */
        Slot* clone() const
        { return new ConstMethodSlot(*this); }

        /** Returns a pointer to this object's internal Callable. */
        virtual const void* callable() const
        { return &_method; }

        virtual bool opened(const Connection& c)
        {
            Connectable& connectable = _method.object();
            return connectable.opened(c);
        }

        virtual void closed(const Connection& c) 
        {
            Connectable& connectable = _method.object();
            connectable.closed(c);
        }
        virtual bool equals(const Slot& slot) const
        {
            const ConstMethodSlot* ms = dynamic_cast<const ConstMethodSlot*>(&slot);
            return ms ? (_method == ms->_method) : false;
        }

    private:
        ConstMethod<R, ClassT${comma_arg_tmpl_types}> _method;
};
EOF
;
}

print << "EOF"
/**
  Creates and returns a ConstMethodSlot for the given object/method pair.
*/
template <class R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
ConstMethodSlot<R,BaseT${comma_arg_tmpl_types}> slot( ClassT & obj, R (BaseT::*memFunc)(${arg_tmpl_types}) const )
{
    return ConstMethodSlot<R,ClassT${comma_arg_tmpl_types}>( callable( obj, memFunc ) );
}
EOF
;
print "// END_ConstMethod ${argc}\n";


print "// BEGIN_Method ${argc}\n";

if( $main_inst ) {
print << "EOF"
/**
The Method class wraps member functions for use with the signals/slots framework.
*/
template < typename R,typename ClassT,${arg_tmpl_decl_main_inst}>
class Method : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
} else {
print << "EOF"
template < typename R, typename ClassT${comma_arg_tmpl_decl}>
class Method<R,ClassT${comma_arg_tmpl_types_all}> : public Callable<R${comma_arg_tmpl_types_all}>
EOF
;
}

print << "EOF"
{
    public:
        /** Convenience typedef of the wrapped member function signature. */
        typedef R (ClassT::*MemFuncT)(${arg_tmpl_types});

        /** Wraps the given object/member pair. */
        explicit Method(ClassT& object, MemFuncT ptr)
        : _object(&object), _memFunc(ptr)
        { }

        /** Deeply copies rhs. */
        Method(const Method& rhs)
        : Callable<R${comma_arg_tmpl_types_all}>()
        { this->operator=(rhs); }


        /** Returns a reference to this object's wrapped ClassT object. */
        ClassT& object()
        { return *_object;}

        /** Returns a const reference to this object's wrapped ClassT object. */
        const ClassT& object() const
        { return *_object;}

        /** Returns a reference to this object's wrapped MemFuncT. */
        const MemFuncT& method() const
        { return _memFunc;}

        /**
          Passes on all arguments to the wrapped object/member pair and returns
          the result of that member.
        */
        inline R operator()(${arg_type_list_named}) const
        { return (_object->*_memFunc)(${arg_params_names}); }

        /**
        Creates a copy of this object and returns it. The caller
        owns the returned object.
        */
        Method<R, ClassT${comma_arg_tmpl_types_all}>* clone() const
        { return new Method(*this); }

        /** Deeply copies rhs. */
        Method& operator=(const Method& rhs)
        {
            if( this != &rhs ) {
                _object = rhs._object;
                _memFunc = rhs._memFunc;
            }
            return (*this);
        }

        /** Returns true if rhs and this object point to the same object
            and method. */
        bool operator==(const Method& rhs) const
        {
            return (_object == rhs._object) &&
                   (_memFunc == rhs._memFunc);
        }

    private:
        ClassT* _object;
        MemFuncT _memFunc;
};

/**
Creates and returns a Method object for the given object/method pair.
*/
template <class R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
Method<R,ClassT${comma_arg_tmpl_types}> callable( ClassT & obj, R (BaseT::*ptr)(${arg_type_list_named}))
{
    return Method<R,ClassT${comma_arg_tmpl_types}>(obj,ptr);
}
EOF
;

if( $main_inst ) {
print << "EOF"
/**
  MethodSlot wraps Method objects so that they can act as Slots.
*/
template < typename R, typename ClassT,${arg_tmpl_decl_main_inst}>
class MethodSlot : public BasicSlot<R${comma_arg_tmpl_types_all}>
{
    public:
        /** Wraps the given Method object. */
        MethodSlot(const Method<R, ClassT${comma_arg_tmpl_types}>& method)
        : _method( method )
        {}

        /**
        Creates a copy of this object and returns it. The caller
        owns the returned object.
        */
        Slot* clone() const
        { return new MethodSlot(*this); }

        /** Returns a pointer to this object's internal Callable. */
        virtual const void* callable() const
        { return &_method; }

        virtual bool opened(const Connection& c)
        {
            Connectable& connectable = _method.object();
            return connectable.opened(c);
        }

        virtual void closed(const Connection& c) 
        {
            Connectable& connectable = _method.object();
            connectable.closed(c);
        }

        virtual bool equals(const Slot& slot) const
        {
            const MethodSlot* ms = dynamic_cast<const MethodSlot*>(&slot);
            return ms ? (_method == ms->_method) : false;
        }


    private:
        Method<R, ClassT${comma_arg_tmpl_types}> _method;
};
EOF
;
}

print << "EOF"
/** Creates and returns a MethodSlot object for the given object/member pair. */
template <class R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
MethodSlot<R,BaseT${comma_arg_tmpl_types}> slot( ClassT & obj, R (BaseT::*memFunc)(${arg_tmpl_types}) )
{
    return MethodSlot<R,ClassT${comma_arg_tmpl_types}>( callable( obj, memFunc ) );
}

// END_Method ${argc}
EOF
;


print "// BEGIN_Delegate ${argc}\n";

if( $main_inst ) {
print << "EOF"
/**
A Delegate is essentially a Signal with only a single target slot.
*/
template < typename R,${arg_tmpl_decl_main_inst}>
class Delegate : public DelegateBase
EOF
;
} else {
print << "EOF"
template < typename R${comma_arg_tmpl_decl}>
class Delegate<R${comma_arg_tmpl_types_all}> : public DelegateBase
EOF
;
}

print << "EOF"
    {
        public:
            typedef Callable<R${comma_arg_tmpl_types}> CallableT;

        public:
            /** Does nothing. */
            Delegate()
            { }

            /** Deeply copies rhs. */
            Delegate(const Delegate& rhs)
            {
                DelegateBase::operator=(rhs);
            }

            /** Connects this object to the given slot and returns that Connection. */
            Connection connect(const BasicSlot<R${comma_arg_tmpl_types}>& slot)
            {
                return Connection(*this, slot.clone() );
            }

            /**
              Passes on all arguments to the connected slot and returns the return value
              of that slot. If no slot is connect then an exception is thrown.
            */
            inline R call(${arg_type_list_named}) const
            {
                if( !_target.valid() ) {
                    throw std::logic_error("Delegate<R${comma_arg_tmpl_types}>::call(): Delegate not connected");
                }
                const CallableT* cb = static_cast<const CallableT*>( _target.slot().callable() );
                return cb->call(${arg_params_names});
            }

            /**
              Passes on all arguments to the connected slot and ignores the return value. If
              No slot is connected, the call is silently ignored.
            */
            inline void invoke(${arg_type_list_named}) const
            {
                if( !_target.valid() ) {
                    return;
                }
                const CallableT* cb = static_cast<const CallableT*>( _target.slot().callable() );
                cb->call(${arg_params_names});
            }

            /** Identical to call(...). */
            R operator()(${arg_type_list_named}) const
            { return this->call(${arg_params_names}); }
    };
EOF
;

if( $main_inst ) {
print << "EOF"
/**
DelegateSlot wraps Deletegate object so that they can behave like Slots.
*/
template < typename R,${arg_tmpl_decl_main_inst}>
class DelegateSlot : public BasicSlot<R${comma_arg_tmpl_types_all}>
{
        public:
            /** Wraps the given Delegate. */
            DelegateSlot(Delegate<R, ${arg_tmpl_types_all}>& delegate)
            : _method( delegate, &Delegate<R,${arg_tmpl_types_all}>::call )
            {}

            /** Creates a copy of this object and returns it. Caller owns the returned object. */
            BasicSlot<R,${arg_tmpl_types_all}>* clone() const
            { return new DelegateSlot(*this); }

            /** Returns a pointer to this object's internal Callable. */
            virtual const void* callable() const
            {
                return &_method;
            }

            virtual bool opened(const Connection& c)
            {
                Connectable& connectable = _method.object();
                return connectable.opened(c);
            }

            virtual void closed(const Connection& c)
            {
                Connectable& connectable = _method.object();
                connectable.closed(c);
            }

            virtual bool equals(const Slot& slot) const
            {
                const DelegateSlot* ds = dynamic_cast<const DelegateSlot*>(&slot);
                return ds ? (_method == ds->_method) : false;
            }

        private:
            mutable ConstMethod<R, Delegate<R, ${arg_tmpl_types_all}>, ${arg_tmpl_types_all} > _method;
};

/** Creates and returns a DelegateSlot for the given Delegate. */
    template < typename R${comma_arg_tmpl_decl}>
    DelegateSlot<R${comma_arg_tmpl_types}> slot( Delegate<R${comma_arg_tmpl_types}>& delegate )
    { return DelegateSlot<R${comma_arg_tmpl_types}>( delegate ); }

EOF
;
}


print << "EOF"
    /** Connect a Delegate to another Delegate.
    */
    template <typename R${comma_arg_tmpl_decl}>
    Connection connect(Delegate<R${comma_arg_tmpl_types}>& delegate, Delegate<R${comma_arg_tmpl_types}>& receiver)
    {
        return connect( delegate,  slot(receiver) );
    }

    /** Connect a Delegate to a Slot.
    */
    template <typename R${comma_arg_tmpl_decl}>
    Connection connect(Delegate<R${comma_arg_tmpl_types}>& delegate, const BasicSlot<R${comma_arg_tmpl_types}>& slot)
    {
        return Connection(delegate, slot.clone() );
    }


    /** Connect a Delegate to a function.
    */
    template <typename R${comma_arg_tmpl_decl}>
    Connection connect(Delegate<R${comma_arg_tmpl_types}>& delegate, R(*func)(${arg_tmpl_types}))
    {
        return connect( delegate, slot(func) );
    }


    /** Connect a Delegate to a member function.
    */
    template <typename R, class BaseT, class ClassT${comma_arg_tmpl_decl}>
    Connection connect(Delegate<R${comma_arg_tmpl_types}>& delegate, BaseT& object, R(ClassT::*memFunc)(${arg_tmpl_types}))
    {
        return connect( delegate, slot(object, memFunc) );
    }

    /** Connect a Delegate to a const member function.
    */
    template <typename R, class ClassT${comma_arg_tmpl_decl}>
    Connection connect(Delegate<R${comma_arg_tmpl_args}>& delegate, ClassT& object, R(ClassT::*memFunc)(${arg_tmpl_types}) const)
    {
        return connect( delegate, slot(object, memFunc) );
    }


// END_Delegate
EOF
;


########################################################################
# Finally, we reach the end...
print << "EOF"
} // namespace $NS
#endif // ${include_guard}
EOF
;

1;
