# Makefile for jam
#
# macOS (Apple clang, invoked as cc)
# make -f Makefile.macos
#
# Native slice only: make -f Makefile.macos ARCHES=
# use -DPT_MCHECK for memory usage statistics

CC = cc
ARCHES = -arch x86_64 -arch arm64
MINVER = -mmacosx-version-min=11.0
CFLAGS = -O2 $(ARCHES) $(MINVER)
TARGET = -o jam

SOURCES = \
	builtins.c class.c command.c compile.c constants.c debug.c execcmd.c execunix.c \
	fileunix.c filesys.c function.c frames.c glob.c hash.c hcache.c hdrmacro.c \
	headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c md5.c mem.c modules.c \
	native.c object.c option.c output.c parse.c pathunix.c pathsys.c cwd.c regexp.c rules.c scan.c \
	search.c strings.c subst.c timestamp.c variable.c w32_getreg.c \
	modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c \
	modules/order.c

all:
	$(CC) $(TARGET) $(CFLAGS) $(SOURCES)
