# Makefile for jam

# NT (with Microsoft compiler)
# People with DevStudio settings already in shell environment.
#
# Unset conflicting MAKEFLAGS when QNX SDK is installed
#
CC = cl /nologo
CFLAGS = -DNT /RTC1 /MT /Os -wd4996 kernel32.lib advapi32.lib
TARGET = /Fejam

SOURCES = \
	command.c compile.c debug.c execnt.c expand.c filent.c glob.c \
	hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c \
	make.c make1.c newstr.c option.c parse.c pathunix.c regexp.c \
	rules.c scan.c search.c subst.c timestamp.c variable.c \
	modules.c strings.c filesys.c builtins.c pwd.c class.c \
	w32_getreg.c native.c modules/set.c modules/path.c modules/regex.c \
	modules/property-set.c modules/sequence.c modules/order.c

all:
	$(CC) $(TARGET) $(CFLAGS) $(SOURCES) $(LINKLIBS)
