name: CI

on:
  push:
    branches:
      - main

jobs:
  Windows-x64-Debug:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run jam.bat
        run: .\jam.bat

  Ubuntu-2024-Debug:
    runs-on: ubuntu-2024
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run jam.sh
        run: ./jam.sh
